/* The real simulation, with no mocked physics or browser dependencies. */
const assert=require('node:assert/strict');
const {Game,MAPS,W,H,STEP}=require('../src/engine.js');
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS',name);}
function advance(g,seconds,events=[]){for(let n=0;n<Math.ceil(seconds/STEP);n++){g.update(STEP);events.push(...g.drainEvents());}return events;}
function ready(opts={}){const g=new Game({humans:2,bots:0,squad:2,seed:124,...opts});advance(g,1.25);return g;}
function flat(opts={}){const g=ready(opts);g.terrain.mask.fill(0);g.terrain.heights.fill(850);for(let y=850;y<H;y++)g.terrain.mask.fill(1,y*W,(y+1)*W);for(const [i,u]of g.units.entries()){u.x=200+i*300;u.y=849.9;u.vx=u.vy=0;u.ground=true;}g.barrels=[];g.wind=0;return g;}
function isolate(g){g.units.slice(1).forEach((u,i)=>{u.x=2400+i*80;u.y=849.9;});}
function invariant(g){for(const u of g.units){assert.ok(Number.isFinite(u.x)&&Number.isFinite(u.y)&&Number.isFinite(u.vx)&&Number.isFinite(u.vy));assert.ok(u.hp>=0&&u.hp<=120);}for(const t of g.teams)for(const ammo of t.ammo)assert.ok(ammo>=0);}
test('All maps safely support 2–6 teams and squads of 2, 4 and 6',()=>{for(const map of Object.keys(MAPS))for(let humans=2;humans<=6;humans++)for(const squad of [2,4,6]){const g=ready({humans,squad,map});assert.equal(g.units.length,humans*squad);assert.ok(g.units.every(u=>u.hp===120&&u.y<g.water));invariant(g);}});
test('Solo includes a bot; six local players cap the roster at 36',()=>{assert.equal(new Game({humans:1,bots:0}).teams.length,2);const g=new Game({humans:6,bots:5,squad:6});assert.equal(g.teams.length,6);assert.equal(g.units.length,36);assert.ok(g.teams.every(t=>!t.bot));});
test('The turn introduction blocks actions before opening control',()=>{const g=new Game({humans:2,bots:0});assert.equal(g.phase,'intro');assert.equal(g.fire(),false);advance(g,1.3);assert.equal(g.humanTurn(),true);});
test('Pause freezes the timer and projectile physics',()=>{const g=flat();g.setAim(65,40);g.fire();const before=JSON.stringify(g.snapshot()),px=g.projectiles[0].x,timer=g.turnTime;g.paused=true;advance(g,4);assert.equal(JSON.stringify(g.snapshot()),before);assert.equal(g.turnTime,timer);assert.equal(g.projectiles[0].x,px);g.paused=false;advance(g,.3);assert.notEqual(g.projectiles[0].x,px);});
test('Movement follows slopes and consumes a finite budget',()=>{for(const map of Object.keys(MAPS)){const g=ready({map}),before=g.active.x;g.keys.right=true;advance(g,1.5);assert.ok(g.active.x>before+60,map);assert.ok(g.energy<180);g.keys.right=false;invariant(g);}});
test('Jumping leaves the floor and lands without sinking',()=>{const g=flat(),y=g.active.y;g.jump();advance(g,.3);assert.ok(g.active.y<y-35);advance(g,2);assert.ok(Math.abs(g.active.y-y)<3);assert.equal(g.active.hp,120);assert.equal(g.active.ground,true);});
test('A crater removes support and the engineer falls into it',()=>{const g=flat(),u=g.active,y=u.y;assert.ok(g.terrain.crater(u.x,u.y+8,70)>5000);advance(g,.5);assert.ok(u.y>y+25);assert.ok(!g.terrain.solid(u.x,y));});
test('Downhill aiming works to both the left and right',()=>{const g=flat();for(const a of [-30,210]){g.setAim(a,40);const p=g.makeProjectile(g.active,g.angle,g.power,3);assert.ok(p.vy>0);assert.equal(Math.sign(p.vx),a<0?1:-1);}});
test('Only one action is allowed and ammunition is spent once',()=>{const g=flat();g.weapon=2;const ammo=g.teams[0].ammo[2];assert.ok(g.fire());assert.equal(g.fire(),false);assert.equal(g.teams[0].ammo[2],ammo-1);assert.equal(g.selectWeapon(1),false);});
test('Arcs destroy terrain and resolve into the next team turn',()=>{const g=flat();isolate(g);g.setAim(25,22);g.fire();const e=advance(g,9);assert.ok(e.some(x=>x.type==='explosion'));assert.ok(g.terrain.holes.length>0);assert.equal(g.active.team,1);});
test('Capacitor bounces and detonates on its fuse',()=>{const g=flat();isolate(g);g.weapon=1;g.setAim(10,12);g.fire();const e=advance(g,3.5);assert.ok(e.some(x=>x.type==='bounce'));assert.equal(e.filter(x=>x.type==='explosion').length,1);assert.equal(g.projectiles.length,0);});
test('EMP damages and pushes multiple rivals',()=>{const g=flat(),a=g.units[1],b=g.units[3];a.x=460;b.x=550;g.explosion(505,825,2,0);assert.ok(a.hp<120&&b.hp<120);assert.ok(a.vx<0&&b.vx>0);assert.ok(a.vy<0&&b.vy<0);});
test('Rail ignores gravity and wind but collides with a thin wall',()=>{const g=flat();isolate(g);g.wind=23;let p=g.makeProjectile(g.active,0,90,3),vx=p.vx,vy=p.vy;g.traceStep(p,STEP);assert.equal(p.vx,vx);assert.equal(p.vy,vy);const wall=280;for(let y=750;y<850;y++)g.terrain.mask[y*W+wall]=1;let result='';for(let i=0;i<20&&!result;i++)result=g.traceStep(p,STEP);assert.equal(result,'hit');assert.ok(Math.abs(p.x-wall)<3);});
test('Cluster splits into five independent charges',()=>{const g=flat();isolate(g);g.weapon=4;g.setAim(60,40);g.fire();let split=false;for(let i=0;i<200;i++){g.update();if(g.drainEvents().some(e=>e.type==='split')){split=true;break;}}assert.ok(split);assert.equal(g.projectiles.length,5);assert.equal(new Set(g.projectiles.map(p=>p.id)).size,5);assert.ok(advance(g,7).filter(e=>e.type==='explosion').length>=3);});
test('Mortar makes a larger crater and deals more damage than an arc',()=>{const a=flat(),b=flat();a.explosion(a.units[1].x,825,0,0);b.explosion(b.units[1].x,825,5,0);assert.ok(b.units[1].hp<a.units[1].hp);assert.ok(b.terrain.holes[0].r>a.terrain.holes[0].r);});
test('Tesla chains three enemies without harming an intervening ally',()=>{const g=flat({squad:3}),enemies=g.units.filter(u=>u.team===1),ally=g.units[2];enemies.forEach((u,i)=>u.x=350+i*150);ally.x=420;g.weapon=6;assert.ok(g.fire());assert.ok(enemies.every(u=>u.hp<120));assert.equal(ally.hp,120);assert.equal(g.drainEvents().filter(e=>e.type==='lightning').length,3);});
test('Out-of-range Tesla keeps the ammo and the current turn',()=>{const g=flat();isolate(g);g.weapon=6;const ammo=g.teams[0].ammo[6];assert.equal(g.fire(),false);assert.equal(g.phase,'aim');assert.equal(g.teams[0].ammo[6],ammo);});
test('Drill excavates a tunnel and stops after bounded penetration',()=>{const g=flat();isolate(g);g.weapon=7;g.setAim(-28,30);g.fire();let largest=0;const e=[];for(let i=0;i<240&&g.projectiles.length;i++){const p=g.projectiles[0];g.update();largest=Math.max(largest,p.drilled);e.push(...g.drainEvents());}assert.ok(e.some(x=>x.type==='drill'));assert.ok(e.some(x=>x.type==='explosion'));assert.ok(largest>=130&&largest<140);assert.ok(g.terrain.holes.length>5);});
test('Airstrike sends five charges around the chosen position',()=>{const g=flat();isolate(g);g.weapon=8;g.aimTarget={x:1200,y:850};g.fire();assert.equal(g.projectiles.length,5);assert.deepEqual(g.projectiles.map(p=>Math.round(p.x)),[1080,1140,1200,1260,1320]);assert.equal(advance(g,7).filter(e=>e.type==='explosion').length,5);});
test('Repair caps life at 120, consumes a charge and ends the turn',()=>{const g=flat();g.active.hp=100;g.weapon=9;const ammo=g.teams[0].ammo[9];g.fire();assert.equal(g.active.hp,120);assert.equal(g.teams[0].ammo[9],ammo-1);assert.equal(g.phase,'settle');});
test('Full-health repair preserves ammunition',()=>{const g=flat();g.weapon=9;const ammo=g.teams[0].ammo[9];assert.equal(g.fire(),false);assert.equal(g.teams[0].ammo[9],ammo);assert.equal(g.phase,'aim');});
test('Barrels chain once and preserve damage attribution',()=>{const g=flat();g.barrels=[{x:440,y:850,alive:true},{x:495,y:850,alive:true}];g.explosion(400,829,0,0);assert.ok(g.barrels.every(b=>!b.alive));assert.equal(g.drainEvents().filter(e=>e.type==='explosion').length,3);assert.ok(g.teams[0].damage>0);});
test('Health and ammunition supplies can be collected',()=>{const g=flat();g.active.hp=70;g.crates=[{x:g.active.x,y:g.active.y,kind:'health',alive:true,landed:true}];advance(g,.05);assert.equal(g.active.hp,105);const ammo=g.teams[0].ammo[1];g.crates.push({x:g.active.x,y:g.active.y,kind:'ammo',alive:true,landed:true});advance(g,.05);assert.equal(g.teams[0].ammo[1],ammo+1);});
test('Water eliminates once and credits the last attacker',()=>{const g=flat(),u=g.units[1];u.y=g.water+20;u.lastHit=0;advance(g,.2);assert.equal(u.hp,0);assert.equal(g.teams[0].kills,1);advance(g,.3);assert.equal(g.teams[0].kills,1);});
test('Timeout skips eliminated teams and rotates engineers',()=>{const g=ready({humans:3,squad:3});g.units.filter(u=>u.team===1).forEach(u=>{u.hp=0;u.eliminated=true;});advance(g,48);assert.equal(g.active.team,2);g.settle(.1);advance(g,1.5);assert.equal(g.active.team,0);assert.notEqual(g.active.id,0);});
test('Rising water begins on round twelve',()=>{const g=flat();g.turn=11*g.teams.length;const water=g.water;g.nextTurn();assert.equal(g.round,12);assert.equal(g.water,water-32);assert.ok(g.drainEvents().some(e=>e.type==='tide'));});
test('Victory and simultaneous elimination produce a single result',()=>{for(const draw of [false,true]){const g=flat();for(const u of g.units)if(draw||u.team===1){u.hp=0;u.eliminated=true;}g.checkWinner();g.checkWinner();assert.equal(g.phase,'over');assert.equal(g.winner,draw?null:0);assert.equal(g.drainEvents().filter(e=>e.type==='victory').length,1);}});
test('Each difficulty produces a legal shot and completes its turn',()=>{for(const difficulty of ['easy','normal','hard']){const g=ready({humans:1,bots:1,squad:4,difficulty});g.nextTurn();advance(g,15);assert.ok(g.turn>=3,difficulty);invariant(g);}});
test('Full 36-engineer matches finish on every map without invalid physics',()=>{const used=new Set();for(const [i,map]of Object.keys(MAPS).entries()){const g=new Game({humans:1,bots:5,squad:6,map,difficulty:['easy','normal','hard','normal'][i],seed:55});g.teams.forEach(t=>t.bot=true);let frames=0;while(g.phase!=='over'&&frames<60*1800){g.update();for(const e of g.drainEvents())if(e.type==='shot')used.add(e.weapon);frames++;if(frames%600===0)invariant(g);}assert.equal(g.phase,'over',map+' must finish');invariant(g);console.log('    '+map+': '+g.turn+' turns, '+Math.round(frames/60)+' simulated seconds');}assert.equal(used.size,10,'Bots must exercise all ten tools across the matches');});
console.log('\n'+passed+' integration checks passed.');
