/* Electrodle: los catálogos: componentes, científicos y fórmulas.
   Solo datos, sin DOM. UMD: `ElectroDatos` en la página, `module.exports`
   en Node (tests/electro.test.cjs comprueba que cada ficha esté completa).

   Las columnas de cada modo de tabla son atributos que se comparan con los
   del objetivo: iguales (verde), con algo en común (amarillo, solo en las
   listas) o distintos (rojo). Las numéricas y las ordenadas llevan además
   una flecha que dice hacia dónde está el objetivo. */
(function (raiz, fabrica) {
  if (typeof module === "object" && module.exports) module.exports = fabrica();
  else raiz.ElectroDatos = fabrica();
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";

  /* Épocas en orden: la flecha de la columna sale de este orden. Son
     tramos y no años porque «el año en que se inventó la resistencia» no
     existe; el tramo sí se puede defender. */
  const EPOCAS = ["Antes de 1900", "1900-1944", "1945-1969", "1970 en adelante"];

  /* ---------- componentes ----------
     alias: otros nombres con que se busca (condensador, termocupla…) ·
     f: familia · fn: funciones · t: terminales del encapsulado típico ·
     p: polarizado (conectarlo al revés lo daña o deja de cumplir su
     función) · ref: designador habitual en un esquemático · e: época
     (índice de EPOCAS) · d: lo que se cuenta al acertar. */
  const COMPONENTES = [
    { id: "resistencia", alias: ["Resistor"], n: "Resistencia", f: "Pasivo", fn: ["Limitar"], t: 2, p: false, ref: "R", e: 0,
      d: "Se opone al paso de la corriente: V = I·R. Su valor se lee en las bandas de colores." },
    { id: "potenciometro", n: "Potenciómetro", f: "Pasivo", fn: ["Limitar", "Ajustar"], t: 3, p: false, ref: "RV", e: 0,
      d: "Una resistencia con un cursor que se desliza sobre ella: es un divisor de voltaje que se ajusta a mano." },
    { id: "capacitor", alias: ["Condensador"], n: "Capacitor", f: "Pasivo", fn: ["Almacenar", "Filtrar"], t: 2, p: false, ref: "C", e: 0,
      d: "Dos placas separadas por un aislante que guardan carga: Q = C·V. Su antepasado es la botella de Leyden (1745)." },
    { id: "electrolitico", alias: ["Condensador electrolítico"], n: "Capacitor electrolítico", f: "Pasivo", fn: ["Almacenar", "Filtrar"], t: 2, p: true, ref: "C", e: 0,
      d: "Mucha capacidad en poco espacio gracias a una capa de óxido finísima. Al revés se hincha o revienta." },
    { id: "cvariable", alias: ["Condensador variable"], n: "Capacitor variable", f: "Pasivo", fn: ["Ajustar", "Filtrar"], t: 2, p: false, ref: "C", e: 1,
      d: "Placas que se entrelazan al girar un eje: así se sintonizaban las radios antiguas." },
    { id: "supercap", alias: ["Supercapacitor", "Ultracapacitor"], n: "Supercondensador", f: "Pasivo", fn: ["Almacenar"], t: 2, p: true, ref: "C", e: 2,
      d: "Capacidades de faradios en una lata pequeña, gracias a la doble capa eléctrica. Entre un capacitor y una batería." },
    { id: "inductor", alias: ["Bobina", "Choke"], n: "Inductor", f: "Pasivo", fn: ["Almacenar", "Filtrar"], t: 2, p: false, ref: "L", e: 0,
      d: "Una bobina de alambre que guarda energía en su campo magnético y se opone a los cambios de corriente." },
    { id: "transformador", alias: ["Trafo"], n: "Transformador", f: "Pasivo", fn: ["Convertir", "Aislar"], t: 4, p: false, ref: "T", e: 0,
      d: "Dos bobinas sobre un núcleo: sube o baja el voltaje alterno en la razón de sus vueltas." },
    { id: "cristal", alias: ["Oscilador", "Xtal"], n: "Cristal de cuarzo", f: "Pasivo", fn: ["Oscilar", "Filtrar"], t: 2, p: false, ref: "Y", e: 1,
      d: "Vibra por piezoelectricidad a una frecuencia muy estable: el reloj de casi todo lo digital." },
    { id: "fusible", alias: ["Fuse"], n: "Fusible", f: "Protección", fn: ["Proteger"], t: 2, p: false, ref: "F", e: 0,
      d: "Un hilo que se funde cuando pasa más corriente de la debida, y se sacrifica para salvar el resto." },
    { id: "varistor", alias: ["MOV"], n: "Varistor", f: "Protección", fn: ["Proteger"], t: 2, p: false, ref: "RV", e: 2,
      d: "Su resistencia cae en picada sobre cierto voltaje: se traga los picos de la red." },
    { id: "termistor", n: "Termistor", f: "Sensor", fn: ["Sensar"], t: 2, p: false, ref: "TH", e: 1,
      d: "Una resistencia que cambia mucho con la temperatura (NTC baja, PTC sube)." },
    { id: "ldr", alias: ["Fotoresistencia"], n: "Fotorresistencia (LDR)", f: "Sensor", fn: ["Sensar"], t: 2, p: false, ref: "R", e: 0,
      d: "Su resistencia baja cuando le llega luz. La fotoconductividad del selenio se descubrió en 1873." },
    { id: "diodo", alias: ["Rectificador"], n: "Diodo", f: "Semiconductor", fn: ["Rectificar"], t: 2, p: true, ref: "D", e: 1,
      d: "Deja pasar la corriente en un solo sentido, de ánodo a cátodo." },
    { id: "zener", n: "Diodo Zener", f: "Semiconductor", fn: ["Regular", "Proteger"], t: 2, p: true, ref: "D", e: 2,
      d: "Conduce al revés a un voltaje preciso: una referencia de tensión de bolsillo." },
    { id: "led", alias: ["Diodo emisor de luz"], n: "LED", f: "Semiconductor", fn: ["Emitir luz"], t: 2, p: true, ref: "D", e: 2,
      d: "Un diodo que emite luz al conducir. El primero visible, rojo, es de Nick Holonyak en 1962." },
    { id: "fotodiodo", n: "Fotodiodo", f: "Semiconductor", fn: ["Sensar"], t: 2, p: true, ref: "D", e: 2,
      d: "Un diodo que convierte luz en corriente; se usa polarizado en inversa." },
    { id: "schottky", n: "Diodo Schottky", f: "Semiconductor", fn: ["Rectificar", "Conmutar"], t: 2, p: true, ref: "D", e: 2,
      d: "Unión metal-semiconductor: cae poco voltaje y conmuta muy rápido." },
    { id: "bjt", alias: ["Transistor bipolar"], n: "Transistor BJT", f: "Semiconductor", fn: ["Amplificar", "Conmutar"], t: 3, p: true, ref: "Q", e: 2,
      d: "Base, colector y emisor: una corriente pequeña en la base controla una grande. El primer transistor nació en Bell Labs en 1947." },
    { id: "mosfet", alias: ["Transistor MOS"], n: "MOSFET", f: "Semiconductor", fn: ["Amplificar", "Conmutar"], t: 3, p: true, ref: "Q", e: 2,
      d: "El voltaje de la compuerta abre o cierra el canal. Es el dispositivo más fabricado de la historia." },
    { id: "jfet", n: "JFET", f: "Semiconductor", fn: ["Amplificar", "Conmutar"], t: 3, p: true, ref: "Q", e: 2,
      d: "Transistor de efecto de campo de unión: conduce sin voltaje en la compuerta y se estrangula al aplicarlo." },
    { id: "igbt", n: "IGBT", f: "Semiconductor", fn: ["Conmutar"], t: 3, p: true, ref: "Q", e: 3,
      d: "Compuerta de MOSFET y salida de bipolar: el músculo de los inversores y los trenes eléctricos." },
    { id: "tiristor", n: "Tiristor (SCR)", f: "Semiconductor", fn: ["Conmutar", "Rectificar"], t: 3, p: true, ref: "Q", e: 2,
      d: "Un pulso en la compuerta lo enciende y queda conduciendo hasta que la corriente cae a cero." },
    { id: "triac", n: "TRIAC", f: "Semiconductor", fn: ["Conmutar"], t: 3, p: true, ref: "Q", e: 2,
      d: "Dos tiristores en antiparalelo con una sola compuerta: controla corriente alterna, como en un dimmer." },
    { id: "diac", n: "DIAC", f: "Semiconductor", fn: ["Conmutar"], t: 2, p: false, ref: "D", e: 2,
      d: "Conduce en ambos sentidos al superar su voltaje de ruptura. Suele disparar a un TRIAC." },
    { id: "optoacoplador", n: "Optoacoplador", f: "Semiconductor", fn: ["Aislar", "Conmutar"], t: 4, p: true, ref: "U", e: 2,
      d: "Un LED y un fototransistor en la misma cápsula: pasa la señal con luz y sin conexión eléctrica." },
    { id: "fototransistor", n: "Fototransistor", f: "Semiconductor", fn: ["Sensar", "Amplificar"], t: 2, p: true, ref: "Q", e: 2,
      d: "Un transistor cuya base es la luz: detecta y amplifica a la vez." },
    { id: "opamp", alias: ["Opamp", "Op-amp"], n: "Amplificador operacional", f: "Circuito integrado", fn: ["Amplificar", "Filtrar"], t: 8, p: true, ref: "U", e: 2,
      d: "Ganancia enorme entre dos entradas; con realimentación hace de todo. El 741 es de 1968." },
    { id: "555", alias: ["NE555"], n: "Temporizador 555", f: "Circuito integrado", fn: ["Oscilar", "Temporizar"], t: 8, p: true, ref: "U", e: 3,
      d: "Diseñado por Hans Camenzind y lanzado en 1972: osciladores y temporizadores con dos resistencias y un capacitor." },
    { id: "regulador", alias: ["7805", "LM7805"], n: "Regulador de voltaje (7805)", f: "Circuito integrado", fn: ["Regular"], t: 3, p: true, ref: "U", e: 3,
      d: "Entrada, tierra y salida: entrega 5 V estables aunque la entrada varíe." },
    { id: "nand", alias: ["7400"], n: "Compuerta NAND (7400)", f: "Circuito integrado", fn: ["Lógica"], t: 14, p: true, ref: "U", e: 2,
      d: "Cuatro compuertas NAND en catorce pines. Con NAND se puede construir cualquier otra función lógica." },
    { id: "rele", alias: ["Relay"], n: "Relé", f: "Electromecánico", fn: ["Conmutar", "Aislar"], t: 5, p: false, ref: "K", e: 0,
      d: "Una bobina que al energizarse mueve un contacto: un circuito pequeño manda a uno grande." },
    { id: "interruptor", alias: ["Switch", "Pulsador"], n: "Interruptor", f: "Electromecánico", fn: ["Conmutar"], t: 2, p: false, ref: "SW", e: 0,
      d: "Abre o cierra el circuito a mano. El más simple de todos." },
    { id: "motor", alias: ["Motor de corriente continua"], n: "Motor DC", f: "Electromecánico", fn: ["Convertir"], t: 2, p: false, ref: "M", e: 0,
      d: "Convierte energía eléctrica en giro; al invertir la polaridad gira al revés." },
    { id: "parlante", alias: ["Altavoz", "Bocina"], n: "Parlante", f: "Electromecánico", fn: ["Convertir"], t: 2, p: false, ref: "LS", e: 1,
      d: "Una bobina en un imán empuja un cono: la corriente se vuelve sonido. El de bobina móvil es de 1925." },
    { id: "microfono", n: "Micrófono electret", f: "Sensor", fn: ["Sensar", "Convertir"], t: 2, p: true, ref: "MK", e: 2,
      d: "Una membrana con carga permanente y un JFET adentro. Inventado en Bell Labs en 1962." },
    { id: "bateria", alias: ["Pila"], n: "Batería", f: "Fuente", fn: ["Alimentar", "Almacenar"], t: 2, p: true, ref: "BT", e: 0,
      d: "Energía química convertida en voltaje continuo. Volta apiló la primera pila en 1800." },
    { id: "celdasolar", alias: ["Panel solar", "Fotovoltaica"], n: "Celda solar", f: "Fuente", fn: ["Alimentar", "Convertir"], t: 2, p: true, ref: "SC", e: 2,
      d: "Un diodo grande que convierte luz en electricidad. La primera de silicio práctica es de Bell Labs, 1954." },
    { id: "termopar", alias: ["Termocupla", "Thermocouple"], n: "Termopar", f: "Sensor", fn: ["Sensar", "Convertir"], t: 2, p: true, ref: "TC", e: 0,
      d: "Dos metales distintos unidos en una punta generan un voltaje que depende de la temperatura (efecto Seebeck, 1821)." },
    { id: "hall", n: "Sensor de efecto Hall", f: "Sensor", fn: ["Sensar"], t: 3, p: true, ref: "U", e: 2,
      d: "Mide campo magnético: el campo desvía a los portadores y aparece un voltaje transversal." },
    { id: "triodo", alias: ["Válvula", "Tubo"], n: "Triodo (tubo de vacío)", f: "Tubo de vacío", fn: ["Amplificar"], t: 3, p: true, ref: "V", e: 1,
      d: "Cátodo, rejilla y placa en el vacío: el Audion de Lee de Forest (1906) fue el primer amplificador." },
    { id: "antena", n: "Antena", f: "Pasivo", fn: ["Radiar"], t: 1, p: false, ref: "AE", e: 0,
      d: "Convierte corrientes en ondas electromagnéticas y al revés. Hertz las usó en 1887 para probar que existían." },
    { id: "ferrita", n: "Perla de ferrita", f: "Pasivo", fn: ["Filtrar"], t: 2, p: false, ref: "FB", e: 2,
      d: "Un cilindro de ferrita que se come el ruido de alta frecuencia: el bulto en los cables de los cargadores." }
  ];

  /* ---------- científicos ----------
     pais: nacionalidad (lista; con una en común se pinta amarillo) ·
     nace / muere: años · area: lista · u: unidad con su nombre ("SI",
     "CGS", "Otra" o "No") · nobel. */
  const CIENTIFICOS = [
    { id: "ohm", n: "Georg Simon Ohm", pais: ["Alemania"], nace: 1789, muere: 1854, area: ["Circuitos"], u: "SI", nobel: false,
      d: "Encontró que la corriente es proporcional al voltaje: la ley de Ohm (1827). El ohmio (Ω) lleva su nombre." },
    { id: "volta", n: "Alessandro Volta", pais: ["Italia"], nace: 1745, muere: 1827, area: ["Electroquímica"], u: "SI", nobel: false,
      d: "Inventó la pila voltaica en 1800, la primera fuente de corriente continua. De él viene el voltio." },
    { id: "ampere", n: "André-Marie Ampère", pais: ["Francia"], nace: 1775, muere: 1836, area: ["Electromagnetismo"], u: "SI", nobel: false,
      d: "Fundó la electrodinámica: dos corrientes se atraen o se repelen. Unidad: el amperio." },
    { id: "faraday", n: "Michael Faraday", pais: ["Reino Unido"], nace: 1791, muere: 1867, area: ["Electromagnetismo", "Electroquímica"], u: "SI", nobel: false,
      d: "Descubrió la inducción electromagnética (1831). El faradio, unidad de capacidad, honra su nombre." },
    { id: "henry", n: "Joseph Henry", pais: ["EE. UU."], nace: 1797, muere: 1878, area: ["Electromagnetismo"], u: "SI", nobel: false,
      d: "Descubrió la autoinducción y construyó electroimanes enormes. El henrio mide la inductancia." },
    { id: "coulomb", n: "Charles-Augustin de Coulomb", pais: ["Francia"], nace: 1736, muere: 1806, area: ["Electrostática"], u: "SI", nobel: false,
      d: "Midió con una balanza de torsión la fuerza entre cargas: cae con el cuadrado de la distancia." },
    { id: "tesla", n: "Nikola Tesla", pais: ["Serbia", "EE. UU."], nace: 1856, muere: 1943, area: ["Potencia", "Electromagnetismo"], u: "SI", nobel: false,
      d: "El motor de inducción y el sistema polifásico de corriente alterna. El tesla mide la densidad de flujo magnético." },
    { id: "weber", n: "Wilhelm Weber", pais: ["Alemania"], nace: 1804, muere: 1891, area: ["Electromagnetismo"], u: "SI", nobel: false,
      d: "Con Gauss construyó un telégrafo en 1833 y midió con precisión el magnetismo. El weber es la unidad de flujo." },
    { id: "siemens", n: "Werner von Siemens", pais: ["Alemania"], nace: 1816, muere: 1892, area: ["Potencia", "Telecomunicaciones"], u: "SI", nobel: false,
      d: "Dínamo autoexcitada, telégrafos y la empresa que lleva su apellido. El siemens mide la conductancia." },
    { id: "hertz", n: "Heinrich Hertz", pais: ["Alemania"], nace: 1857, muere: 1894, area: ["Electromagnetismo", "Telecomunicaciones"], u: "SI", nobel: false,
      d: "Generó y detectó ondas de radio en 1887, confirmando a Maxwell. El hercio mide la frecuencia." },
    { id: "joule", n: "James Prescott Joule", pais: ["Reino Unido"], nace: 1818, muere: 1889, area: ["Termodinámica"], u: "SI", nobel: false,
      d: "Midió el equivalente mecánico del calor y el calor que disipa una corriente: P = I²R." },
    { id: "watt", n: "James Watt", pais: ["Reino Unido"], nace: 1736, muere: 1819, area: ["Termodinámica"], u: "SI", nobel: false,
      d: "Mejoró la máquina de vapor con el condensador separado. El vatio mide la potencia." },
    { id: "kelvin", n: "William Thomson (Lord Kelvin)", pais: ["Reino Unido"], nace: 1824, muere: 1907, area: ["Termodinámica", "Telecomunicaciones"], u: "SI", nobel: false,
      d: "La escala absoluta de temperatura y la teoría del cable telegráfico transatlántico." },
    { id: "gauss", n: "Carl Friedrich Gauss", pais: ["Alemania"], nace: 1777, muere: 1855, area: ["Matemáticas", "Electromagnetismo"], u: "CGS", nobel: false,
      d: "El príncipe de los matemáticos: su ley relaciona el flujo eléctrico con la carga encerrada." },
    { id: "oersted", alias: ["Oersted", "Orsted"], n: "Hans Christian Ørsted", pais: ["Dinamarca"], nace: 1777, muere: 1851, area: ["Electromagnetismo"], u: "CGS", nobel: false,
      d: "En 1820 vio que una corriente desvía una brújula: la electricidad y el magnetismo estaban unidos." },
    { id: "maxwell", n: "James Clerk Maxwell", pais: ["Reino Unido"], nace: 1831, muere: 1879, area: ["Electromagnetismo"], u: "CGS", nobel: false,
      d: "Unificó electricidad, magnetismo y luz en cuatro ecuaciones y predijo las ondas electromagnéticas." },
    { id: "franklin", n: "Benjamin Franklin", pais: ["EE. UU."], nace: 1706, muere: 1790, area: ["Electrostática"], u: "CGS", nobel: false,
      d: "Llamó positiva y negativa a la carga, e inventó el pararrayos. El franklin es la unidad de carga del sistema CGS." },
    { id: "gilbert", n: "William Gilbert", pais: ["Reino Unido"], nace: 1544, muere: 1603, area: ["Electrostática", "Electromagnetismo"], u: "CGS", nobel: false,
      d: "En «De Magnete» (1600) acuñó la palabra «eléctrico» y propuso que la Tierra es un imán." },
    { id: "kirchhoff", n: "Gustav Kirchhoff", pais: ["Alemania"], nace: 1824, muere: 1887, area: ["Circuitos"], u: "No", nobel: false,
      d: "Sus dos leyes, de corrientes en los nodos y de voltajes en las mallas, resuelven cualquier circuito." },
    { id: "edison", n: "Thomas Edison", pais: ["EE. UU."], nace: 1847, muere: 1931, area: ["Potencia", "Telecomunicaciones"], u: "No", nobel: false,
      d: "La ampolleta práctica, el fonógrafo y la primera central eléctrica comercial, en corriente continua." },
    { id: "westinghouse", n: "George Westinghouse", pais: ["EE. UU."], nace: 1846, muere: 1914, area: ["Potencia"], u: "No", nobel: false,
      d: "Apostó por la corriente alterna de Tesla y ganó la «guerra de las corrientes» contra Edison." },
    { id: "marconi", n: "Guglielmo Marconi", pais: ["Italia"], nace: 1874, muere: 1937, area: ["Telecomunicaciones"], u: "No", nobel: true,
      d: "La telegrafía sin hilos: cruzó el Atlántico por radio en 1901. Nobel de Física en 1909." },
    { id: "braun", n: "Ferdinand Braun", pais: ["Alemania"], nace: 1850, muere: 1918, area: ["Telecomunicaciones", "Electrónica"], u: "No", nobel: true,
      d: "El tubo de rayos catódicos y la rectificación en cristales. Compartió el Nobel de 1909 con Marconi." },
    { id: "shockley", n: "William Shockley", pais: ["EE. UU."], nace: 1910, muere: 1989, area: ["Electrónica"], u: "No", nobel: true,
      d: "Teoría del transistor de unión y la ecuación del diodo. Nobel de Física en 1956." },
    { id: "bardeen", n: "John Bardeen", pais: ["EE. UU."], nace: 1908, muere: 1991, area: ["Electrónica"], u: "No", nobel: true,
      d: "Coinventor del transistor y de la teoría BCS de la superconductividad: el único con dos Nobel de Física." },
    { id: "brattain", n: "Walter Brattain", pais: ["EE. UU."], nace: 1902, muere: 1987, area: ["Electrónica"], u: "No", nobel: true,
      d: "Armó con Bardeen el primer transistor de punto de contacto en diciembre de 1947." },
    { id: "kilby", n: "Jack Kilby", pais: ["EE. UU."], nace: 1923, muere: 2005, area: ["Electrónica"], u: "No", nobel: true,
      d: "Hizo el primer circuito integrado en Texas Instruments (1958). Nobel de Física en 2000." },
    { id: "noyce", n: "Robert Noyce", pais: ["EE. UU."], nace: 1927, muere: 1990, area: ["Electrónica"], u: "No", nobel: false,
      d: "El circuito integrado monolítico de silicio y la fundación de Fairchild e Intel." },
    { id: "thevenin", n: "Léon Charles Thévenin", pais: ["Francia"], nace: 1857, muere: 1926, area: ["Circuitos"], u: "No", nobel: false,
      d: "Cualquier red lineal vista desde dos terminales es una fuente con una resistencia en serie." },
    { id: "norton", n: "Edward Lawry Norton", pais: ["EE. UU."], nace: 1898, muere: 1983, area: ["Circuitos"], u: "No", nobel: false,
      d: "El dual de Thévenin: una fuente de corriente con una resistencia en paralelo." },
    { id: "bode", n: "Hendrik Wade Bode", pais: ["EE. UU."], nace: 1905, muere: 1982, area: ["Control", "Circuitos"], u: "No", nobel: false,
      d: "Sus diagramas de magnitud y fase en escala logarítmica son el pan de cada día del control." },
    { id: "nyquist", n: "Harry Nyquist", pais: ["Suecia", "EE. UU."], nace: 1889, muere: 1976, area: ["Telecomunicaciones", "Control"], u: "No", nobel: false,
      d: "El criterio de estabilidad que lleva su nombre y el ruido térmico. Muestrear al doble viene de su trabajo." },
    { id: "shannon", n: "Claude Shannon", pais: ["EE. UU."], nace: 1916, muere: 2001, area: ["Telecomunicaciones", "Computación"], u: "Otra", nobel: false,
      d: "Fundó la teoría de la información (1948) y llevó el álgebra de Boole a los circuitos de relés." },
    { id: "fourier", n: "Joseph Fourier", pais: ["Francia"], nace: 1768, muere: 1830, area: ["Matemáticas"], u: "No", nobel: false,
      d: "Cualquier señal periódica es una suma de senos y cosenos. Lo descubrió estudiando el calor." },
    { id: "laplace", n: "Pierre-Simon Laplace", pais: ["Francia"], nace: 1749, muere: 1827, area: ["Matemáticas"], u: "No", nobel: false,
      d: "Su transformada convierte ecuaciones diferenciales en álgebra: el idioma de los circuitos y el control." },
    { id: "heaviside", n: "Oliver Heaviside", pais: ["Reino Unido"], nace: 1850, muere: 1925, area: ["Electromagnetismo", "Telecomunicaciones"], u: "No", nobel: false,
      d: "Escribió las ecuaciones de Maxwell en la forma vectorial de hoy y acuñó «impedancia» e «inductancia»." },
    { id: "steinmetz", n: "Charles Proteus Steinmetz", pais: ["Alemania", "EE. UU."], nace: 1865, muere: 1923, area: ["Potencia"], u: "No", nobel: false,
      d: "Llevó los números complejos (fasores) al análisis de corriente alterna." },
    { id: "deforest", n: "Lee de Forest", pais: ["EE. UU."], nace: 1873, muere: 1961, area: ["Electrónica"], u: "No", nobel: false,
      d: "El Audion (1906), el triodo que hizo posible amplificar una señal." },
    { id: "fleming", n: "John Ambrose Fleming", pais: ["Reino Unido"], nace: 1849, muere: 1945, area: ["Electrónica"], u: "No", nobel: false,
      d: "La válvula de Fleming (1904), el primer diodo de vacío. Y las reglas de la mano." },
    { id: "lamarr", alias: ["Hedy Kiesler"], n: "Hedy Lamarr", pais: ["Austria", "EE. UU."], nace: 1914, muere: 2000, area: ["Telecomunicaciones"], u: "No", nobel: false,
      d: "Actriz e inventora: patentó en 1942 el salto de frecuencia, antepasado del Wi-Fi y el Bluetooth." },
    { id: "clarke", n: "Edith Clarke", pais: ["EE. UU."], nace: 1883, muere: 1959, area: ["Potencia"], u: "No", nobel: false,
      d: "Primera mujer con un máster en ingeniería eléctrica del MIT (1919). Su transformada simplifica los sistemas trifásicos." },
    { id: "musschenbroek", n: "Pieter van Musschenbroek", pais: ["Países Bajos"], nace: 1692, muere: 1761, area: ["Electrostática"], u: "No", nobel: false,
      d: "Inventó la botella de Leyden entre 1745 y 1746: el primer capacitor." },
    { id: "black", n: "Harold Stephen Black", pais: ["EE. UU."], nace: 1898, muere: 1983, area: ["Electrónica", "Control"], u: "No", nobel: false,
      d: "Ideó el amplificador con realimentación negativa en 1927, camino al trabajo en un ferry." },
    { id: "morse", n: "Samuel Morse", pais: ["EE. UU."], nace: 1791, muere: 1872, area: ["Telecomunicaciones"], u: "No", nobel: false,
      d: "El telégrafo eléctrico de un hilo y el código de puntos y rayas." },
    { id: "bell", n: "Alexander Graham Bell", pais: ["Reino Unido", "EE. UU.", "Canadá"], nace: 1847, muere: 1922, area: ["Telecomunicaciones"], u: "Otra", nobel: false,
      d: "Patentó el teléfono en 1876. El belio (y su décima parte, el decibel) lleva su nombre." },
    { id: "wheatstone", n: "Charles Wheatstone", pais: ["Reino Unido"], nace: 1802, muere: 1875, area: ["Circuitos", "Telecomunicaciones"], u: "No", nobel: false,
      d: "Popularizó el puente que mide resistencias desconocidas y construyó telégrafos." },
    { id: "kalman", n: "Rudolf Kálmán", pais: ["Hungría", "EE. UU."], nace: 1930, muere: 2016, area: ["Control"], u: "No", nobel: false,
      d: "El filtro de Kalman estima el estado de un sistema con ruido; llevó al Apolo a la Luna." },
    { id: "galvani", n: "Luigi Galvani", pais: ["Italia"], nace: 1737, muere: 1798, area: ["Electroquímica"], u: "No", nobel: false,
      d: "Hizo saltar ancas de rana con electricidad. Su discusión con Volta llevó a la pila." }
  ];

  /* ---------- fórmulas ----------
     `f` es la fórmula en fichas. Una ficha que empieza con letra es una
     variable (se tapa y se destapa de a una): «V_out» lleva subíndice y
     «I^2» exponente. Las que empiezan con «!» son texto fijo (π, e, log,
     cos, la d de una derivada; «!log_10» lleva subíndice); los números y los signos van siempre a la
     vista. {fr:[arriba, abajo]} es una fracción y {rz:[...]} una raíz. */
  const fr = (a, b) => ({ fr: [a, b] }), rz = (...a) => ({ rz: a });
  const FORMULAS = [
    { id: "ohm", n: "Ley de Ohm", a: "Circuitos", f: ["V", "=", "I", "·", "R"],
      d: "El voltaje en una resistencia es proporcional a la corriente que la atraviesa." },
    { id: "potencia", n: "Potencia eléctrica", a: "Circuitos", f: ["P", "=", "V", "·", "I"],
      d: "La energía por segundo que entrega o consume un elemento." },
    { id: "joule", n: "Efecto Joule", a: "Circuitos", f: ["P", "=", "I^2", "·", "R"],
      d: "El calor que disipa una resistencia crece con el cuadrado de la corriente." },
    { id: "serie", n: "Resistencias en serie", a: "Circuitos", f: ["R_eq", "=", "R_1", "+", "R_2", "+", "R_3"],
      d: "En serie, las resistencias simplemente se suman." },
    { id: "paralelo", n: "Resistencias en paralelo", a: "Circuitos", f: [fr(["1"], ["R_eq"]), "=", fr(["1"], ["R_1"]), "+", fr(["1"], ["R_2"])],
      d: "En paralelo se suman las conductancias: la equivalente siempre es menor que la menor." },
    { id: "cserie", n: "Capacitores en serie", a: "Circuitos", f: [fr(["1"], ["C_eq"]), "=", fr(["1"], ["C_1"]), "+", fr(["1"], ["C_2"])],
      d: "Los capacitores en serie se combinan como las resistencias en paralelo." },
    { id: "divisor", n: "Divisor de voltaje", a: "Circuitos", f: ["V_out", "=", "V_in", "·", fr(["R_2"], ["R_1", "+", "R_2"])],
      d: "Dos resistencias en serie reparten el voltaje en proporción a su valor." },
    { id: "divcorriente", n: "Divisor de corriente", a: "Circuitos", f: ["I_1", "=", "I", "·", fr(["R_2"], ["R_1", "+", "R_2"])],
      d: "Por la rama de menor resistencia pasa más corriente." },
    { id: "lck", n: "Ley de corrientes de Kirchhoff", a: "Circuitos", f: ["!Σ", "I_k", "=", "0"],
      d: "Lo que entra a un nodo es lo que sale: la carga se conserva." },
    { id: "lvk", n: "Ley de voltajes de Kirchhoff", a: "Circuitos", f: ["!Σ", "V_k", "=", "0"],
      d: "Al recorrer una malla cerrada, las subidas y bajadas de voltaje suman cero." },
    { id: "carga", n: "Carga de un capacitor", a: "Circuitos", f: ["Q", "=", "C", "·", "V"],
      d: "La carga guardada es proporcional al voltaje entre las placas." },
    { id: "energiac", n: "Energía en un capacitor", a: "Circuitos", f: ["E", "=", fr(["1"], ["2"]), "C", "V^2"],
      d: "La energía guardada en el campo eléctrico entre las placas." },
    { id: "energial", n: "Energía en un inductor", a: "Circuitos", f: ["E", "=", fr(["1"], ["2"]), "L", "I^2"],
      d: "La energía guardada en el campo magnético de la bobina." },
    { id: "taurc", n: "Constante de tiempo RC", a: "Circuitos", f: ["τ", "=", "R", "·", "C"],
      d: "En un τ el capacitor llega al 63 % de su carga final." },
    { id: "taurl", n: "Constante de tiempo RL", a: "Circuitos", f: ["τ", "=", fr(["L"], ["R"])],
      d: "Cuánto tarda la corriente de una bobina en acercarse a su valor final." },
    { id: "xc", n: "Reactancia capacitiva", a: "Corriente alterna", f: ["X_C", "=", fr(["1"], ["2", "!π", "f", "C"])],
      d: "Un capacitor deja pasar mejor las frecuencias altas." },
    { id: "xl", n: "Reactancia inductiva", a: "Corriente alterna", f: ["X_L", "=", "2", "!π", "f", "L"],
      d: "Una bobina se opone más cuanto mayor es la frecuencia." },
    { id: "resonancia", n: "Frecuencia de resonancia LC", a: "Corriente alterna", f: ["f_0", "=", fr(["1"], ["2", "!π", rz("L", "C")])],
      d: "Donde las reactancias del inductor y del capacitor se igualan y se cancelan." },
    { id: "corte", n: "Frecuencia de corte de un filtro RC", a: "Señales", f: ["f_c", "=", fr(["1"], ["2", "!π", "R", "C"])],
      d: "Donde la salida cae 3 dB: la frontera entre lo que pasa y lo que no." },
    { id: "omega", n: "Frecuencia angular", a: "Señales", f: ["ω", "=", "2", "!π", "f"],
      d: "Radianes por segundo en vez de ciclos por segundo." },
    { id: "rlc", n: "Impedancia RLC serie", a: "Corriente alterna", f: ["Z", "=", "R", "+", "!j", "(", "ω", "L", "−", fr(["1"], ["ω", "C"]), ")"],
      d: "La parte real disipa; la imaginaria guarda y devuelve energía." },
    { id: "rms", n: "Valor eficaz de una sinusoide", a: "Corriente alterna", f: ["V_rms", "=", fr(["V_p"], [rz("2")])],
      d: "El voltaje continuo que calentaría igual una resistencia. Los 220 V de la red son eficaces." },
    { id: "aparente", n: "Potencia aparente", a: "Potencia", f: ["S", "=", "V_rms", "·", "I_rms"],
      d: "Se mide en voltamperios: es lo que tiene que aguantar el cableado." },
    { id: "fp", n: "Factor de potencia", a: "Potencia", f: ["FP", "=", fr(["P"], ["S"]), "=", "!cos", "φ"],
      d: "Qué parte de la potencia aparente hace trabajo útil." },
    { id: "trifasica", n: "Potencia trifásica", a: "Potencia", f: ["P", "=", rz("3"), "V_L", "I_L", "!cos", "φ"],
      d: "La potencia activa de un sistema trifásico equilibrado, con valores de línea." },
    { id: "transformador", n: "Relación de transformación", a: "Potencia", f: [fr(["V_1"], ["V_2"]), "=", fr(["N_1"], ["N_2"])],
      d: "El voltaje se reparte en la razón de las vueltas de cada bobinado." },
    { id: "sincronica", n: "Velocidad sincrónica", a: "Potencia", f: ["n_s", "=", fr(["120", "f"], ["p"])],
      d: "Las rpm del campo giratorio de un motor de alterna, con p polos." },
    { id: "coulomb", n: "Ley de Coulomb", a: "Electromagnetismo", f: ["F", "=", "k", fr(["q_1", "q_2"], ["r^2"])],
      d: "La fuerza entre dos cargas cae con el cuadrado de la distancia." },
    { id: "faraday", n: "Ley de Faraday", a: "Electromagnetismo", f: ["ε", "=", "−", "N", fr(["!dΦ"], ["!dt"])],
      d: "Un flujo magnético que cambia induce un voltaje; el signo menos es la ley de Lenz." },
    { id: "lorentz", n: "Fuerza de Lorentz", a: "Electromagnetismo", f: ["F", "=", "q", "(", "E", "+", "v", "×", "B", ")"],
      d: "La fuerza sobre una carga en movimiento dentro de campos eléctrico y magnético." },
    { id: "ampere", n: "Ley de Ampère", a: "Electromagnetismo", f: ["!∮", "B", "·", "!dl", "=", "μ_0", "I_enc"],
      d: "La circulación del campo magnético alrededor de un camino cerrado mide la corriente que encierra." },
    { id: "gauss", n: "Ley de Gauss", a: "Electromagnetismo", f: ["!∮", "E", "·", "!dA", "=", fr(["Q_enc"], ["ε_0"])],
      d: "El flujo eléctrico que sale de una superficie cerrada mide la carga de adentro." },
    { id: "biot", n: "Ley de Biot-Savart", a: "Electromagnetismo", f: ["!dB", "=", fr(["μ_0"], ["4", "!π"]), fr(["I", "!dl", "×", "r̂"], ["r^2"])],
      d: "El campo magnético que produce cada trocito de un cable con corriente." },
    { id: "solenoide", n: "Inductancia de un solenoide", a: "Electromagnetismo", f: ["L", "=", fr(["μ_0", "N^2", "A"], ["l"])],
      d: "Crece con el cuadrado de las vueltas: doblar las vueltas cuadruplica la inductancia." },
    { id: "placas", n: "Capacitor de placas paralelas", a: "Electromagnetismo", f: ["C", "=", fr(["ε_0", "ε_r", "A"], ["d"])],
      d: "Más área o menos separación, más capacidad." },
    { id: "resistividad", n: "Resistencia de un conductor", a: "Circuitos", f: ["R", "=", fr(["ρ", "ℓ"], ["A"])],
      d: "Un cable más largo o más delgado resiste más." },
    { id: "ohmlocal", n: "Ley de Ohm puntual", a: "Electromagnetismo", f: ["J", "=", "σ", "E"],
      d: "La versión microscópica de la ley de Ohm: densidad de corriente y campo eléctrico." },
    { id: "luz", n: "Velocidad de la luz", a: "Electromagnetismo", f: ["c", "=", fr(["1"], [rz("μ_0", "ε_0")])],
      d: "Maxwell la obtuvo de constantes eléctricas y magnéticas: la luz es una onda electromagnética." },
    { id: "poynting", n: "Vector de Poynting", a: "Electromagnetismo", f: ["S", "=", "E", "×", "H"],
      d: "Hacia dónde fluye la energía electromagnética y cuánta por metro cuadrado." },
    { id: "inversor", n: "Ganancia del amplificador inversor", a: "Electrónica", f: ["G", "=", "−", fr(["R_f"], ["R_in"])],
      d: "Con un amplificador operacional ideal, la ganancia solo depende de dos resistencias." },
    { id: "noinversor", n: "Ganancia del amplificador no inversor", a: "Electrónica", f: ["G", "=", "1", "+", fr(["R_f"], ["R_g"])],
      d: "Nunca baja de 1: con R_f = 0 es un seguidor de voltaje." },
    { id: "shockley", n: "Ecuación del diodo de Shockley", a: "Electrónica", f: ["I", "=", "I_S", "(", "!e", { sup: ["V", "/", "n", "V_T"] }, "−", "1", ")"],
      d: "La corriente de un diodo crece exponencialmente con el voltaje directo." },
    { id: "beta", n: "Ganancia de corriente del BJT", a: "Electrónica", f: ["I_C", "=", "β", "·", "I_B"],
      d: "La corriente de colector es β veces la de base, típicamente entre 50 y 300." },
    { id: "decibel", n: "Ganancia en decibeles", a: "Señales", f: ["G_dB", "=", "20", "!log_10", "(", fr(["V_out"], ["V_in"]), ")"],
      d: "20 veces el logaritmo de la razón de voltajes: ×10 son 20 dB." },
    { id: "shannon", n: "Capacidad de canal de Shannon", a: "Señales", f: ["C", "=", "B", "!log_2", "(", "1", "+", fr(["S"], ["N"]), ")"],
      d: "Los bits por segundo máximos que caben en un canal con ancho de banda B y ruido." },
    { id: "nyquist", n: "Criterio de Nyquist", a: "Señales", f: ["f_s", ">", "2", "f_max"],
      d: "Para reconstruir una señal hay que muestrearla a más del doble de su frecuencia más alta." }
  ];

  return { EPOCAS, COMPONENTES, CIENTIFICOS, FORMULAS };
});
