(function(){
'use strict';
const {Game,Renderer,Soundtrack,MAPS,WEAPONS,COLORS,TEAM_NAMES,clamp}=CB,$=id=>document.getElementById(id);
const iconPaths={
 arc:'M18 2 7 16h9l-2 14 12-18h-9z',
 grenade:'M13 5h7v4h-7z M20 6h5v5 M12 10h10l3 6v11H9V16z M12 17h10 M12 22h10',
 emp:'M16 11a5 5 0 1 0 0 10 5 5 0 0 0 0-10 M7 7a13 13 0 0 0 0 18 M25 7a13 13 0 0 1 0 18 M16 3v4 M16 25v4 M3 16h4 M25 16h4',
 rail:'M3 13h19v8H3z M7 13V9h12v4 M22 15h8 M22 19h8 M8 21v6h5v-6 M4 16h12',
 cluster:'M15 2h3v7h-3z M7 13h6v7H7z M20 13h6v7h-6z M13 23h7v7h-7z M16 10l-6 3 M17 10l6 3 M10 21l5 3 M23 21l-5 3',
 mortar:'M7 25h20 M10 25l3-7 M24 25l-7-7 M10 6l7-4 9 16-7 4z M12 9l7-4 M20 21l3 5',
 tesla:'M15 8v16 M11 24h9v5h-9z M11 9h9 M9 13h13 M7 17h17 M16 3l-4 4h7z M5 5 2 10l5 2-3 6 M27 6l3 5-4 4 3 5',
 drill:'M3 12h12v12H3z M15 10l6 3 8 5-8 5-6 3z M19 13v10 M23 15v6 M5 8h7v4 M6 24v5h5v-5',
 airstrike:'M3 11 14 7l2-5 2 5 11 4-1 4-10-2v7l4 3v3l-6-2-6 2v-3l4-3v-7L4 15z M5 23v6 M27 23v6',
 repair:'M6 9h21v19H6z M11 9V5h11v4 M14 13h5v4h4v5h-4v4h-5v-4h-4v-5h4z'
};
function icon(id){return `<svg viewBox="0 0 32 32" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPaths[id]}"></path></svg>`;}
const artworks={substation:$('environment-art'),alpine:$('environment-alpine'),desert:$('environment-desert'),tidal:$('environment-tidal')};
const soundtrack=new Soundtrack(),renderer=new Renderer($('scene'),$('minimap'),artworks);
let game=null,map='substation',last=performance.now(),accumulator=0,keys={},charging=false,chargeDelay=0,noticeLeft=0,bannerLeft=0,lastUI='',lastSecond=-1,overlay=null,previousPaused=false,returnDialog=null,pointerDrag=null,pinchDistance=0;
const pointers=new Map();
function options(){return{humans:+$('humans').value,bots:+$('bots').value,squad:+$('squad').value,difficulty:$('difficulty').value,map,turnTime:45};}
function savePreferences(){try{localStorage.setItem('circuit-breakers-v2',JSON.stringify({...options(),music:soundtrack.enabled,effects:soundtrack.effects,volume:soundtrack.volume}));}catch{}}
function config(){const h=+$('humans').value,min=h===1?1:0,max=6-h,b=clamp(+$('bots').value||0,min,max);$('bots').innerHTML=Array.from({length:max-min+1},(_,i)=>`<option value="${min+i}">${min+i} ${min+i===1?'bot':'bots'}</option>`).join('');$('bots').value=b;$('difficulty').disabled=b===0;const size=+$('squad').value;$('roster-preview').innerHTML=Array.from({length:h+b},(_,i)=>`<span class="roster-chip" style="color:${COLORS[i]}"><i></i>${i<h?'J'+(i+1):'BOT '+(i-h+1)}</span>`).join('');$('operation-summary').textContent=`${size*(h+b)} ingenieros · ${h+b} equipos`;}
function restorePreferences(){try{const v=JSON.parse(localStorage.getItem('circuit-breakers-v2')||'null');if(v){for(const id of ['humans','squad','difficulty'])if([...$(id).options].some(o=>o.value===String(v[id])))$(id).value=v[id];config();if([...$('bots').options].some(o=>o.value===String(v.bots)))$('bots').value=v.bots;if(MAPS[v.map])map=v.map;soundtrack.enabled=v.music!==false;soundtrack.effects=v.effects!==false;if(Number.isFinite(v.volume))soundtrack.setVolume(v.volume);}}catch{}config();}
function paintMaps(){for(const [key,m]of Object.entries(MAPS)){const canvas=$('thumb-'+key),c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,gradient=c.createLinearGradient(0,0,0,h);gradient.addColorStop(0,m.sky[0]);gradient.addColorStop(1,m.sky[2]);c.fillStyle=gradient;c.fillRect(0,0,w,h);if(artworks[key].complete&&artworks[key].naturalWidth){const image=artworks[key];c.drawImage(image,0,image.naturalHeight*.36,image.naturalWidth,image.naturalHeight*.64,0,0,w,h);}else{c.fillStyle=m.accent;c.beginPath();c.arc(w*.73,h*.27,key==='desert'?12:6,0,Math.PI*2);c.fill();for(let j=0;j<3;j++){c.fillStyle=[m.sky[1],m.ground[1],m.ground[2]][j];c.beginPath();c.moveTo(0,h);for(let x=0;x<=w;x+=5)c.lineTo(x,h*(.52+j*.14)+Math.sin(x*.022+j)*9+Math.sin(x*.04+j)*7);c.lineTo(w,h);c.fill();}}c.fillStyle='#071c2744';c.fillRect(0,0,w,h);}}
function renderMaps(){$('map-cards').innerHTML=Object.entries(MAPS).map(([id,m],i)=>`<button class="map-card ${id===map?'selected':''}" data-map="${id}" aria-pressed="${id===map}" aria-label="${m.name}: ${m.desc}"><canvas id="thumb-${id}" width="420" height="115"></canvas><span class="map-card-number">0${i+1} / 3.2 KM</span><div class="map-card-info"><strong>${m.name}</strong><small>${m.tag}</small><span class="map-check">✓</span></div></button>`).join('');document.querySelectorAll('.map-card').forEach(b=>b.onclick=()=>{map=b.dataset.map;document.querySelectorAll('.map-card').forEach(n=>{n.classList.toggle('selected',n===b);n.setAttribute('aria-pressed',String(n===b));});soundtrack.effect('select');savePreferences();});paintMaps();}
function updateAudioUI(){$('music-btn').innerHTML='♫ <span>MÚSICA '+(soundtrack.enabled?'ON':'OFF')+'</span>';$('music-btn').setAttribute('aria-label',soundtrack.enabled?'Desactivar música':'Activar música');$('music-enabled').checked=soundtrack.enabled;$('effects-enabled').checked=soundtrack.effects;$('music-volume').value=Math.round(soundtrack.volume/.7*100);$('volume-value').textContent=$('music-volume').value+'%';if(soundtrack.failed)$('audio-status').textContent='El navegador no pudo iniciar el audio. Prueba a activar Música nuevamente.';else if(soundtrack.ready)$('audio-status').textContent='Audio activo · Composición original · Sin archivos de red';}
function clearInputs(){keys={};charging=false;pointers.clear();pointerDrag=null;pinchDistance=0;if(game)game.keys={left:false,right:false};$('fire').classList.remove('charging');}
function startGame(){clearInputs();savePreferences();game=new Game(options());overlay=null;returnDialog=null;document.querySelectorAll('.overlay').forEach(e=>e.hidden=true);$('menu').hidden=true;$('hud').hidden=false;$('pause-btn').hidden=false;document.body.classList.add('playing');$('top-label').innerHTML='<i></i> OPERACIÓN EN CURSO';renderer.attach(game);soundtrack.mode='combat';soundtrack.setPause(false);soundtrack.unlock().then(updateAudioUI);lastUI='';lastSecond=-1;noticeLeft=0;bannerLeft=0;$('notice').classList.remove('show');$('notice').textContent='';updateHUD();processEvents();document.activeElement?.blur();}
function mainMenu(){game=null;renderer.game=null;renderer.particles=[];renderer.rings=[];renderer.texts=[];clearInputs();overlay=null;returnDialog=null;document.querySelectorAll('.overlay').forEach(e=>e.hidden=true);$('menu').hidden=false;$('hud').hidden=true;$('pause-btn').hidden=true;document.body.classList.remove('playing');document.body.dataset.phase='menu';$('top-label').innerHTML='<i></i> CENTRO DE OPERACIONES';soundtrack.mode='menu';soundtrack.setPause(false);lastUI='';}
function showNotice(text,duration=3.2){$('notice').textContent=text;$('notice').classList.add('show');noticeLeft=duration;}
function showDialog(id){clearInputs();if(overlay&&overlay!==id){returnDialog=overlay;$(overlay).hidden=true;}else if(!overlay){previousPaused=game?.paused||false;returnDialog=null;}overlay=id;$(id).hidden=false;if(game)game.paused=true;soundtrack.setPause(!!game);updateHUD();$(id).querySelector('button')?.focus();}
function closeDialog(id){$(id).hidden=true;overlay=null;if(returnDialog){overlay=returnDialog;$(overlay).hidden=false;returnDialog=null;}else{if(game)game.paused=previousPaused;soundtrack.setPause(!!game?.paused);}updateHUD();document.activeElement?.blur();}
function pause(){if(!game||game.phase==='over')return;if(overlay){if(overlay==='pause-dialog'){previousPaused=false;closeDialog(overlay);}else closeDialog(overlay);}else showDialog('pause-dialog');}
function renderWeapons(){$('weapons').innerHTML=WEAPONS.map((w,i)=>`<button class="weapon" data-weapon="${i}" aria-label="${w.name}" aria-pressed="false" title="${w.description}"><span class="weapon-key">${(i+1)%10}</span><span class="weapon-ammo"></span>${icon(w.icon)}<span>${w.short}</span></button>`).join('');document.querySelectorAll('.weapon').forEach(b=>b.onclick=()=>{if(game?.selectWeapon(+b.dataset.weapon))updateHUD();});}
function updateHUD(){if(!game)return;const g=game,t=g.teams[g.teamIndex],u=g.active,total=g.options.squad*120,w=WEAPONS[g.weapon];document.documentElement.style.setProperty('--team',t.color);$('teams').innerHTML=g.teams.map(team=>{const members=g.units.filter(v=>v.team===team.id),hp=members.reduce((v,m)=>v+m.hp,0);return `<div class="team-card ${team.id===g.teamIndex?'active':''} ${hp===0?'dead':''}" style="--team:${team.color}"><div class="team-title"><span>${team.bot?'⚙ ':''}${team.name}</span><span>${Math.round(hp)}</span></div><div class="team-health"><i style="width:${hp/total*100}%"></i></div><div class="team-people">${members.map(v=>`<i class="${v.hp<=0?'dead':''}" title="${v.name}: ${v.hp} vida"></i>`).join('')}</div></div>`;}).join('');
  $('unit-name').textContent=u.name;$('unit-role').textContent=u.role;$('unit-health').textContent='♥ '+Math.ceil(u.hp)+' / 120';$('team-name').textContent=t.name;$('turn-kind').textContent=t.bot?'BOT ACTIVO':'TU TURNO';$('map-label').textContent=MAPS[g.options.map].name.toUpperCase();$('round-label').textContent='RONDA '+String(g.round).padStart(2,'0');$('wind-label').textContent=(g.wind<0?'← ':'→ ')+Math.abs(g.wind).toFixed(0)+' km/h';$('weapon-name').textContent=w.name;$('weapon-description').textContent=w.description;$('weapon-stats').textContent=w.type==='repair'?'+45 VIDA':w.type==='chain'?'51 DAÑO · CADENA':w.damage+' DAÑO · '+w.radius+' m';
  const human=g.humanTurn();document.querySelectorAll('.weapon').forEach((b,i)=>{b.classList.toggle('selected',i===g.weapon);b.setAttribute('aria-pressed',String(i===g.weapon));b.querySelector('.weapon-ammo').textContent=t.ammo[i]===Infinity?'∞':t.ammo[i];b.disabled=!human||t.ammo[i]<=0||(i===9&&u.hp>=u.maxHp);});for(const id of ['angle','power','move-left','move-right','jump','skip-turn'])$(id).disabled=!human;$('fire').disabled=!human;$('fire').innerHTML=t.bot?'CALCULANDO…':w.type==='repair'?'REPARAR <span>✚</span>':w.type==='airstrike'?'CONFIRMAR <span>↗</span>':'DISPARAR <span>↗</span>';$('angle').disabled=!human||['repair','chain','airstrike'].includes(w.type);$('power').disabled=!human||['repair','chain','airstrike','rail'].includes(w.type);syncAim();lastUI=[g.phase,g.paused,g.teamIndex,u.hp,g.weapon].join('/');}
function syncAim(){if(!game)return;$('angle').value=Math.round(game.angle);$('power').value=Math.round(game.power);$('angle-out').textContent=Math.round(game.angle)+'°';$('power-out').textContent=Math.round(game.power)+'%';}
function fire(){if(!game?.humanTurn())return;charging=false;$('fire').classList.remove('charging');game.fire();updateHUD();}
function results(){const g=game,w=g.winner!==null?g.teams[g.winner]:null;$('winner-title').textContent=w?w.name+' domina la red.':'Apagón total.';$('winner-title').style.color=w?.color||'#ffc395';$('winner-description').textContent=w?`Operación completada en ${g.turn} turnos. ${g.units.filter(u=>u.team===w.id&&u.hp>0).length} ingenieros regresan a casa.`:'Ninguna cuadrilla sobrevivió. La próxima vez, revisen la puesta a tierra.';$('result-list').innerHTML=[...g.teams].sort((a,b)=>(b.id===g.winner)-(a.id===g.winner)||b.damage-a.damage).map(t=>`<div class="result-row"><span style="color:${t.color}">${t.id===g.winner?'★ ':''}${t.name}</span><small>${t.damage} daño · ${t.kills} bajas</small></div>`).join('');clearInputs();$('results-dialog').hidden=false;overlay='results-dialog';$('pause-btn').hidden=true;soundtrack.mode='menu';soundtrack.effect('victory');}
function processEvents(){if(!game)return;let dirty=false;for(const e of game.drainEvents()){renderer.event(e);if(['explosion','shot','lightning','jump','splash','bounce','heal','pickup','select','turn'].includes(e.type))soundtrack.effect(e.type,e.weapon||1);if(['hud','ready','damage','eliminate','heal','pickup','select'].includes(e.type))dirty=true;if(e.type==='turn'){clearInputs();const team=game.teams[e.team],u=game.units[e.unit];$('banner-team').textContent=team.name;$('banner-unit').textContent=u.name+' · '+u.role+(team.bot?' · BOT':'');$('turn-banner').classList.add('show');bannerLeft=1.65;dirty=true;}if(e.type==='notice')showNotice(e.text);if(e.type==='supply')showNotice('Suministro en camino. Recógelo para recuperar vida o munición.');if(e.type==='tide')showNotice('SOBRECARGA · El nivel del agua está subiendo.',4);if(e.type==='victory')results();}if(dirty)updateHUD();}
function updateInputs(dt){if(!game?.humanTurn())return;game.keys.left=!!keys.a;game.keys.right=!!keys.d;let a=game.angle,p=game.power;if(keys.arrowleft)a+=dt*55;if(keys.arrowright)a-=dt*55;if(keys.arrowup)p+=dt*32;if(keys.arrowdown)p-=dt*32;if(charging){chargeDelay+=dt;if(chargeDelay>.12)p+=dt*30;}$('fire').classList.toggle('charging',charging);game.setAim(a,p);if(charging||keys.arrowleft||keys.arrowright||keys.arrowup||keys.arrowdown)syncAim();}
function frame(now){const delta=Math.min(.12,(now-last)/1000);last=now;accumulator+=delta;let loops=0;while(accumulator>=1/60&&loops<8){if(game){updateInputs(1/60);game.update(1/60);}accumulator-=1/60;loops++;}processEvents();
  if(game){if(!game.paused){if(noticeLeft>0){noticeLeft-=delta;if(noticeLeft<=0)$('notice').classList.remove('show');}if(bannerLeft>0){bannerLeft-=delta;if(bannerLeft<=0)$('turn-banner').classList.remove('show');}}const token=[game.phase,game.paused,game.teamIndex,game.active.hp,game.weapon].join('/');if(token!==lastUI)updateHUD();let second=Math.max(0,Math.ceil(game.turnTime));if(second!==lastSecond){$('timer').textContent=second;$('timer').style.color=second<=10?'#ff9b9e':'';lastSecond=second;}$('mobility-fill').style.transform=`scaleX(${game.energy/240})`;$('zoom-label').textContent=Math.round(renderer.cam.z*100)+'%';document.body.dataset.phase=game.phase;if(game.teams[game.teamIndex].bot&&game.phase==='aim')syncAim();}
  renderer.update(delta);renderer.draw();soundtrack.tick();requestAnimationFrame(frame);
 }
for(const id of ['humans','bots','squad','difficulty'])$(id).onchange=()=>{config();savePreferences();};
$('start-btn').onclick=startGame;$('rematch').onclick=startGame;$('back-menu').onclick=mainMenu;$('quit').onclick=mainMenu;$('brand-home').onclick=e=>{e.preventDefault();if(game)pause();};
$('fire').onclick=fire;$('angle').oninput=e=>{if(game?.humanTurn()){game.setAim(+e.target.value,game.power);syncAim();}};$('power').oninput=e=>{if(game?.humanTurn()){game.setAim(game.angle,+e.target.value);syncAim();}};
$('jump').onclick=()=>{if(game?.humanTurn())game.jump();};$('skip-turn').onclick=()=>{if(game?.humanTurn()){clearInputs();game.settle(.6);updateHUD();}};
for(const [id,key]of[['move-left','a'],['move-right','d']]){const b=$(id);b.onpointerdown=e=>{if(!game?.humanTurn())return;e.preventDefault();b.setPointerCapture(e.pointerId);keys[key]=true;};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>{keys[key]=false;};}
$('pause-btn').onclick=pause;$('resume').onclick=()=>{previousPaused=false;closeDialog('pause-dialog');};$('help-btn').onclick=$('manual-btn').onclick=()=>showDialog('help-dialog');$('pause-help').onclick=()=>showDialog('help-dialog');$('settings-btn').onclick=()=>{showDialog('settings-dialog');soundtrack.unlock().then(updateAudioUI);};document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>closeDialog(b.dataset.close));
$('music-btn').onclick=()=>{soundtrack.setMusic(!soundtrack.enabled);if(soundtrack.enabled)soundtrack.unlock().then(updateAudioUI);updateAudioUI();savePreferences();};$('music-enabled').onchange=e=>{soundtrack.setMusic(e.target.checked);updateAudioUI();savePreferences();};$('effects-enabled').onchange=e=>{soundtrack.effects=e.target.checked;updateAudioUI();savePreferences();};$('music-volume').oninput=e=>{soundtrack.setVolume(+e.target.value/100*.7);updateAudioUI();savePreferences();};
$('zoom-in').onclick=()=>renderer.zoom(1.2);$('zoom-out').onclick=()=>renderer.zoom(1/1.2);$('overview').onclick=()=>renderer.overviewToggle();$('center-camera').onclick=()=>renderer.center();$('minimap').onpointerdown=e=>{if(!game)return;const r=$('minimap').getBoundingClientRect();renderer.lookAt((e.clientX-r.left)/r.width*CB.W,(e.clientY-r.top)/r.height*CB.H);};
function pointerAim(e){if(!game?.humanTurn())return;const p=renderer.screenToWorld(e.clientX,e.clientY);if(WEAPONS[game.weapon].type==='airstrike'){game.aimTarget={x:clamp(p.x,80,CB.W-80),y:p.y};return;}let a=Math.atan2(game.active.y-25-p.y,p.x-game.active.x)*180/Math.PI;if(a<-85)a+=360;game.setAim(a,game.power);syncAim();}
$('scene').oncontextmenu=e=>e.preventDefault();$('scene').onpointerdown=e=>{if(!game||overlay)return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});$('scene').setPointerCapture(e.pointerId);if(pointers.size===2){const [a,b]=[...pointers.values()];pinchDistance=Math.hypot(a.x-b.x,a.y-b.y);pointerDrag=null;return;}pointerDrag={id:e.pointerId,x:e.clientX,y:e.clientY,pan:e.button===2||e.button===1||e.altKey};if(!pointerDrag.pan)pointerAim(e);};
$('scene').onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);if(pinchDistance>0)renderer.zoom(d/pinchDistance,(a.x+b.x)/2,(a.y+b.y)/2);pinchDistance=d;return;}if(pointerDrag?.id===e.pointerId){if(pointerDrag.pan){renderer.pan(e.clientX-pointerDrag.x,e.clientY-pointerDrag.y);pointerDrag.x=e.clientX;pointerDrag.y=e.clientY;}else pointerAim(e);}};
$('scene').onpointerup=$('scene').onpointercancel=$('scene').onlostpointercapture=e=>{pointers.delete(e.pointerId);if(pointerDrag?.id===e.pointerId)pointerDrag=null;if(pointers.size<2)pinchDistance=0;};$('scene').addEventListener('wheel',e=>{if(game&&!overlay){e.preventDefault();renderer.zoom(Math.exp(-e.deltaY*.0013),e.clientX,e.clientY);}},{passive:false});
addEventListener('keydown',e=>{const key=e.key.toLowerCase(),focused=document.activeElement;if(focused?.tagName==='SELECT'||(focused?.tagName==='INPUT'&&focused.type!=='range'))return;if(key==='escape'||key==='p'){if(!e.repeat){if(overlay&&overlay!=='pause-dialog'&&overlay!=='results-dialog')closeDialog(overlay);else pause();}return;}if(!game||overlay)return;if([' ','arrowleft','arrowright','arrowup','arrowdown','a','d','w'].includes(key))e.preventDefault();if(key==='q'&&!e.repeat){renderer.overviewToggle();return;}if(key==='c'&&!e.repeat){renderer.center();return;}if(!game.humanTurn())return;keys[key]=true;if(key==='w'&&!e.repeat)game.jump();if(key===' '&&!e.repeat){charging=true;chargeDelay=0;}if(/^\d$/.test(key)&&!e.repeat){game.selectWeapon(key==='0'?9:+key-1);updateHUD();}});
addEventListener('keyup',e=>{const k=e.key.toLowerCase();keys[k]=false;if(k===' '&&charging){charging=false;$('fire').classList.remove('charging');fire();}});addEventListener('blur',clearInputs);document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInputs();if(game&&game.phase!=='over'&&!overlay)showDialog('pause-dialog');soundtrack.setPause(true);}else{last=performance.now();accumulator=0;if(!game&&!overlay)soundtrack.setPause(false);}});
addEventListener('resize',()=>renderer.resize());Object.values(artworks).forEach(image=>image.addEventListener('load',paintMaps));
restorePreferences();renderMaps();renderWeapons();updateAudioUI();requestAnimationFrame(frame);
})();
