(function(root){
'use strict';
const {W,H,MAPS,WEAPONS,COLORS,clamp,randomSeed}=root.CB;
const TAU=Math.PI*2;
function round(c,x,y,w,h,r=5){c.beginPath();c.roundRect(x,y,w,h,r);}
function line(c,points,color,width=1){c.strokeStyle=color;c.lineWidth=width;c.beginPath();points.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.stroke();}
class Renderer{
 constructor(canvas,mini,images){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.mini=mini;this.mc=mini.getContext('2d');this.images=images;this.width=innerWidth;this.height=innerHeight;this.dpr=Math.min(devicePixelRatio||1,2);this.time=0;this.game=null;this.map='substation';this.terrainCanvas=document.createElement('canvas');this.terrainCanvas.width=W;this.terrainCanvas.height=H;this.tc=this.terrainCanvas.getContext('2d');this.holesDrawn=0;this.particles=[];this.rings=[];this.texts=[];this.bolts=[];this.shake=0;this.flash=0;this.manual=0;this.overview=false;this.area={top:125,bottom:600,height:475,cy:362};this.cam={x:W/2,y:650,z:.75,tx:W/2,ty:650,tz:.75};this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.aimCache=null;this.resize();}
 resize(){this.width=innerWidth;this.height=innerHeight;this.dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.round(this.width*this.dpr);this.canvas.height=Math.round(this.height*this.dpr);this.layout();if(this.game)this.center();}
 layout(){const dock=document.getElementById('combat-dock');const top=this.width<620?126:this.height<610?108:128,bottom=dock&&!dock.hidden&&dock.getBoundingClientRect().height>0?dock.getBoundingClientRect().top-8:this.height-164;this.area={top,bottom:Math.max(top+60,bottom),height:Math.max(60,bottom-top),cy:(top+Math.max(top+60,bottom))/2};}
 attach(game){this.game=game;this.map=game.options.map;this.buildTerrain();this.particles=[];this.rings=[];this.texts=[];this.bolts=[];this.manual=0;this.overview=false;this.aimCache=null;this.layout();this.center(true);}
 focusOffset(){return Math.min(145,Math.max(25,(this.area.height/2-35)/this.cam.tz));}
 center(immediate=false){if(!this.game?.active)return;this.overview=false;this.manual=0;const u=this.game.active;this.cam.tz=clamp(this.area.height/450,.65,1.08);this.cam.tx=u.x+u.facing*140;this.cam.ty=u.y-this.focusOffset();this.clampCamera();if(immediate){this.cam.x=this.cam.tx;this.cam.y=this.cam.ty;this.cam.z=this.cam.tz;}}
 overviewToggle(){this.overview=!this.overview;if(this.overview){this.manual=999;this.cam.tx=W/2;this.cam.ty=590;this.cam.tz=Math.min(this.width/(W+130),this.area.height/1030);}else this.center();}
 zoom(mult,x=this.width/2,y=this.area.cy){if(!this.game)return;const world=this.screenToWorld(x,y),z=clamp(this.cam.tz*mult,Math.min(.25,this.width/W),1.5);this.cam.tx=world.x-(x-this.width/2)/z;this.cam.ty=world.y-(y-this.area.cy)/z;this.cam.tz=z;this.manual=15;this.overview=false;this.clampCamera();}
 pan(dx,dy){this.cam.tx-=dx/this.cam.z;this.cam.ty-=dy/this.cam.z;this.manual=20;this.overview=false;this.clampCamera();}
 lookAt(x,y){this.cam.tx=x;this.cam.ty=y-100;this.manual=15;this.overview=false;this.clampCamera();}
 clampCamera(){const half=this.width/(2*this.cam.tz);this.cam.tx=half>=W/2?W/2:clamp(this.cam.tx,half-100,W-half+100);this.cam.ty=clamp(this.cam.ty,-100,H-50);}
 screenToWorld(x,y){return{x:this.cam.x+(x-this.width/2)/this.cam.z,y:this.cam.y+(y-this.area.cy)/this.cam.z};}
 worldToScreen(x,y){return{x:this.width/2+(x-this.cam.x)*this.cam.z,y:this.area.cy+(y-this.cam.y)*this.cam.z};}
 buildTerrain(){const t=this.game.terrain,m=MAPS[this.map],c=this.tc,rng=randomSeed(m.seed);this.holesDrawn=0;c.clearRect(0,0,W,H);const g=c.createLinearGradient(0,580,0,H);g.addColorStop(0,m.ground[0]);g.addColorStop(.4,m.ground[1]);g.addColorStop(1,m.ground[2]);c.fillStyle=g;c.beginPath();c.moveTo(0,H);for(let x=0;x<W;x+=2)c.lineTo(x,t.heights[x]);c.lineTo(W,H);c.closePath();c.fill();c.save();c.clip();
  for(let layer=0;layer<10;layer++){c.strokeStyle=layer%2?'#f3d6ae11':'#07131d40';c.lineWidth=2+rng()*12;c.beginPath();for(let x=0;x<=W;x+=12){let y=650+layer*57+Math.sin(x*.003+layer)*23+Math.sin(x*.012+layer)*14;x?c.lineTo(x,y):c.moveTo(x,y);}c.stroke();}
  for(let i=0;i<1300;i++){let x=rng()*W,y=580+rng()*620,size=2+rng()*21;c.fillStyle=i%4===0?'#c8c9aa1b':'#08162120';c.beginPath();c.moveTo(x,y);c.lineTo(x+size,y-size*.2);c.lineTo(x+size*.8,y+size*.3);c.lineTo(x-3,y+size*.4);c.closePath();c.fill();}
  for(let i=0;i<165;i++){let x=rng()*W,y=690+rng()*440;line(c,[[x,y],[x+20,y+10],[x+42,y+9],[x+70,y+24]],'#01081325',1.5);}
  c.restore();c.lineJoin='round';c.strokeStyle='#0519228c';c.lineWidth=18;c.beginPath();for(let x=0;x<W;x+=2)x?c.lineTo(x,t.heights[x]+11):c.moveTo(x,t.heights[x]+11);c.stroke();c.strokeStyle=m.grass;c.lineWidth=this.map==='alpine'?11:6;c.beginPath();for(let x=0;x<W;x+=2)x?c.lineTo(x,t.heights[x]):c.moveTo(x,t.heights[x]);c.stroke();
  for(let x=2;x<W-2;x+=5){if(t.heights[x]>1030)continue;let y=t.heights[x],height=2+rng()*7;if(this.map==='alpine'){c.fillStyle='#f5fcf333';c.beginPath();c.ellipse(x,y+3,6,2,0,0,TAU);c.fill();}else{line(c,[[x-2,y],[x-3,y-height],[x+1,y-1],[x+3,y-height*.6]],rng()>.5?m.grass:m.ground[0],1);}}
  for(let i=0;i<150;i++){let x=Math.floor(rng()*W),y=t.heights[x];if(y>1020)continue;c.fillStyle=m.ground[1];c.strokeStyle='#dceac536';c.lineWidth=1;c.beginPath();c.ellipse(x,y-1,2+rng()*8,2+rng()*4,0,0,TAU);c.fill();c.stroke();}
 }
 updateTerrain(){const c=this.tc,t=this.game.terrain;for(;this.holesDrawn<t.holes.length;this.holesDrawn++){const h=t.holes[this.holesDrawn];c.save();c.globalCompositeOperation='destination-out';c.beginPath();c.arc(h.x,h.y,h.r,0,TAU);c.fill();c.restore();c.save();c.globalCompositeOperation='source-atop';c.strokeStyle='#050b10c9';c.lineWidth=8;c.beginPath();c.arc(h.x,h.y,h.r+2,0,TAU);c.stroke();c.strokeStyle='#dba8753b';c.lineWidth=1;c.beginPath();c.arc(h.x,h.y,h.r+6,0,TAU);c.stroke();c.restore();}}
 burst(x,y,color,count=30,speed=190,kind='spark'){count=this.reduced?Math.min(count,12):count;for(let i=0;i<count;i++){const a=Math.random()*TAU,s=Math.random()*speed,life=kind==='smoke'?1.2+Math.random():.45+Math.random()*.7;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-(kind==='smoke'?30:25),life,max:life,color,size:kind==='smoke'?10+Math.random()*16:1.5+Math.random()*3,gravity:kind==='smoke'?-12:200,kind,rotation:Math.random()*6});}if(this.particles.length>1100)this.particles.splice(0,this.particles.length-1100);}
 event(e){if(e.type==='explosion'){this.burst(e.x,e.y,e.color,50,e.radius*3);this.burst(e.x,e.y,'#17282d',13,45,'smoke');this.burst(e.x,e.y,MAPS[this.map].ground[0],23,170,'debris');this.rings.push({x:e.x,y:e.y,r:e.radius,life:.55,max:.55,color:e.color});this.shake=Math.min(14,this.shake+e.radius/11);this.flash=.055;}
  if(e.type==='damage')this.texts.push({x:e.x,y:e.y,text:'−'+e.value,color:'#ffb2a1',life:1.5});
  if(e.type==='heal'){this.texts.push({x:e.x,y:e.y-60,text:'+'+e.gain,color:'#adfbd1',life:1.6});this.rings.push({x:e.x,y:e.y-20,r:62,life:1,max:1,color:'#91efb6'});this.burst(e.x,e.y-25,'#91efb6',22,95);}
  if(e.type==='eliminate'){this.burst(e.x,e.y-25,COLORS[e.team],26,150,'debris');this.texts.push({x:e.x,y:e.y-80,text:e.name+' fuera',color:COLORS[e.team],life:2});}
  if(e.type==='lightning')this.bolts.push({...e,life:.5});
  if(e.type==='splash')this.burst(e.x,e.y,'#acedef',36,185);
  if(e.type==='step'||e.type==='land')this.burst(e.x,e.y,MAPS[this.map].ground[0],e.type==='land'?12:2,e.type==='land'?60:20,'smoke');
  if(e.type==='drill')this.burst(e.x,e.y,'#e8b0ff',4,85);
  if(e.type==='pickup')this.texts.push({x:e.x,y:e.y-60,text:e.text,color:'#ffe9a8',life:2});
  if(e.type==='split')this.burst(e.x,e.y,'#ffce8c',18,130);
  if(e.type==='turn'){this.center();}
  if(e.type==='shot'){this.manual=0;this.overview=false;}
  if(e.type==='victory'&&e.winner!==null)for(let i=0;i<9;i++)this.burst(this.cam.x+(Math.random()-.5)*900,this.cam.y-100-Math.random()*220,COLORS[e.winner],30,200,'debris');
 }
 update(dt){this.time+=dt;const paused=this.game?.paused;if(!paused){for(const p of this.particles){p.life-=dt;p.vy+=p.gravity*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.rotation+=dt*3;}this.particles=this.particles.filter(p=>p.life>0);for(const t of this.texts){t.life-=dt;t.y-=dt*30;}this.texts=this.texts.filter(p=>p.life>0);for(const r of this.rings)r.life-=dt;this.rings=this.rings.filter(r=>r.life>0);for(const b of this.bolts)b.life-=dt;this.bolts=this.bolts.filter(b=>b.life>0);this.shake=Math.max(0,this.shake-dt*28);this.flash=Math.max(0,this.flash-dt);}
  if(this.game){this.manual=Math.max(0,this.manual-dt);if(!this.manual&&!this.overview){const g=this.game,ps=g.projectiles.filter(p=>p.delay<=0);if(ps.length){let x=ps.reduce((v,p)=>v+p.x,0)/ps.length,y=ps.reduce((v,p)=>v+p.y,0)/ps.length;this.cam.tx=x;this.cam.ty=y+35;if(ps.length>1)this.cam.tz=Math.min(this.cam.tz,.72);}else if(g.active?.hp>0){this.cam.tx=g.active.x+g.active.facing*130;this.cam.ty=g.active.y-this.focusOffset();}}
   this.clampCamera();let f=this.reduced?1:1-Math.exp(-dt*5.3);this.cam.x+=(this.cam.tx-this.cam.x)*f;this.cam.y+=(this.cam.ty-this.cam.y)*f;this.cam.z+=(this.cam.tz-this.cam.z)*f;
  }
 }
 background(){const c=this.ctx,w=this.width,h=this.height,map=this.game?this.map:'substation',m=MAPS[map],g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,m.sky[0]);g.addColorStop(.65,m.sky[1]);g.addColorStop(1,m.sky[2]);c.fillStyle=g;c.fillRect(0,0,w,h);
  const art=this.images[map];if(art?.complete&&art.naturalWidth){const scale=Math.max(w/art.naturalWidth,h/art.naturalHeight)*1.09,iw=art.naturalWidth*scale,ih=art.naturalHeight*scale,parallax=this.game?(this.cam.x-W/2)*.024:Math.sin(this.time*.035)*10;c.globalAlpha=this.game?.86:1;c.drawImage(art,(w-iw)/2-parallax,(h-ih)/2-8,iw,ih);c.globalAlpha=1;}
  else{
   const px=this.cam.x*.025;
   if(map==='alpine'){c.save();c.globalCompositeOperation='screen';for(let n=0;n<3;n++){const a=c.createLinearGradient(0,0,0,h*.65);a.addColorStop(0,'#3cdcc600');a.addColorStop(.5,['#51f5bf24','#7280f328','#75e6f222'][n]);a.addColorStop(1,'#45d5c000');c.fillStyle=a;c.beginPath();c.moveTo(0,0);for(let x=0;x<=w;x+=18)c.lineTo(x,h*.21+Math.sin(x*.003+n+this.time*.08)*60+n*25);c.lineTo(w,h*.55);for(let x=w;x>=0;x-=18)c.lineTo(x,h*.35+Math.sin(x*.003+n+this.time*.08)*60+n*25);c.closePath();c.fill();}c.restore();}
   c.fillStyle=map==='desert'?'#ffd4a3':'#d7e7e7';c.shadowColor=m.accent;c.shadowBlur=55;c.beginPath();c.arc(w*.76-px*.1,h*.24,map==='desert'?47:26,0,TAU);c.fill();c.shadowBlur=0;
   for(let layer=0;layer<4;layer++){c.fillStyle=map==='desert'?['#a5787444','#805e6999','#4d4960bb','#283546d9'][layer]:['#7789a34a','#435f8099','#2d4965cc','#1d334adc'][layer];c.beginPath();c.moveTo(-20,h);for(let x=-20;x<=w+30;x+=20){let y=h*(.48+layer*.09)+Math.sin((x+px*(layer+1))*.004+layer)*38+Math.sin((x+px)*.011+layer)*20;if(map==='alpine')y-=Math.abs(Math.sin((x+px)*.006+layer))*65;x===-20?c.lineTo(x,y):c.lineTo(x,y);}c.lineTo(w+30,h);c.fill();}
   if(map==='tidal'){for(let i=0;i<8;i++){let x=i*w/7-px*.2,y=h*.64;c.fillStyle='#152b3b';c.fillRect(x,y-50,62,85);line(c,[[x+30,y],[x+30,y-150],[x+120,y-150]],'#294557',7);line(c,[[x+45,y-151],[x+93,y-191],[x+120,y-151]],'#375364',3);for(let j=0;j<3;j++){c.fillStyle='#d4bc7960';c.fillRect(x+8+j*16,y-34,6,8);}}}
  }
  // Atmospheric layers stay in screen space, with subtle motion and depth.
  const shade=c.createLinearGradient(0,0,0,h);shade.addColorStop(0,'#08131c60');shade.addColorStop(.45,'#0d263000');shade.addColorStop(1,'#07121dd9');c.fillStyle=shade;c.fillRect(0,0,w,h);
  if(!this.reduced){c.fillStyle=m.accent;for(let i=0;i<24;i++){let x=(i*193+this.time*(5+i%4))%(w+40)-20,y=h*.35+((i*87)%Math.max(100,h*.5));c.globalAlpha=.12+(Math.sin(this.time+i)+1)*.08;c.beginPath();c.arc(x,y,i%3===0?1.4:.7,0,TAU);c.fill();}c.globalAlpha=1;}
 }
 drawPylon(c,x,y,s){c.save();c.translate(x,y);c.scale(s,s);c.globalAlpha=.65;line(c,[[-38,0],[-8,-185],[8,-185],[38,0]],'#47616b',3);for(let yy=-25;yy>-160;yy-=30){let a=8+30*(1+yy/185);line(c,[[-a,yy],[a-5,yy-30],[-a+5,yy-30],[a,yy]],'#55727c',2);}line(c,[[-58,-142],[58,-142]],'#5b7680',4);line(c,[[-46,-167],[46,-167]],'#536e79',4);for(let xx of [-48,-29,29,48]){c.fillStyle='#8bafa4';c.fillRect(xx,-143,5,17);}c.restore();}
 decorations(){const c=this.ctx,g=this.game,map=this.map,t=g.terrain;
  for(let i=0;i<7;i++){let x=250+i*470,y=t.heights[Math.floor(x)];if(y>980)continue;
   if(map==='alpine'){c.save();c.translate(x,y+25);line(c,[[0,0],[0,-170]],'#6b8792',6);c.fillStyle='#a7bbc2';c.beginPath();c.arc(0,-170,8,0,TAU);c.fill();c.translate(0,-170);c.rotate(this.reduced?i:this.time*.14+i);for(let j=0;j<3;j++){c.rotate(TAU/3);c.fillStyle='#b7cccf';c.beginPath();c.moveTo(-3,0);c.lineTo(-7,-25);c.lineTo(-2,-87);c.lineTo(4,-40);c.lineTo(4,0);c.closePath();c.fill();}c.restore();}
   else if(map==='desert'){for(let j=0;j<4;j++){const px=x+j*30;line(c,[[px,y+20],[px,y-23]],'#48565c',3);c.save();c.translate(px,y-26);c.rotate(-.23);c.fillStyle='#233e59';c.strokeStyle='#698d9c';c.lineWidth=1;c.fillRect(-17,-14,33,24);c.strokeRect(-17,-14,33,24);line(c,[[-6,-14],[-6,10]],'#779aaa',.7);line(c,[[6,-14],[6,10]],'#779aaa',.7);line(c,[[-17,-2],[16,-2]],'#779aaa',.7);c.restore();}}
   else{this.drawPylon(c,x,y+35,.9);if(i%2===0){c.fillStyle='#304b57';round(c,x+65,y-48,45,82,5);c.fill();for(let j=0;j<8;j++){c.fillStyle='#68847b';c.fillRect(x+62,y-43+j*7,51,3);}c.fillStyle='#a1b19a';c.fillRect(x+80,y-72,12,24);}}
  }
 }
 engineer(c,u,color,active=false,scale=1){
  c.save();c.translate(u.x,u.y);c.scale(scale,scale);const t=this.time,g=this.game,walk=u.ground?Math.sin(u.walk)*4:2,land=u.landing?1-u.landing*.3:1;
  c.fillStyle='#03131b66';c.beginPath();c.ellipse(0,1,19,5,0,0,TAU);c.fill();if(active){c.strokeStyle=color+'88';c.lineWidth=1.5;c.beginPath();c.ellipse(0,2,24+Math.sin(t*3)*2,7,0,0,TAU);c.stroke();}
  c.scale(1,land);c.rotate(u.hurt>0?Math.sin(t*80)*.09:u.ground?Math.sin(t*1.7+u.id)*.014:u.vx*.0002);
  const outline='#0a1d2b';c.lineWidth=1.5;c.strokeStyle=outline;
  // Battery pack and breathing cable.
  const facing=u.facing||1;c.fillStyle='#293d4c';round(c,-facing*13-6,-37,12,26,4);c.fill();c.stroke();c.fillStyle=color;round(c,-facing*13-3,-33,5,12,2);c.fill();c.fillStyle='#6ababe';c.fillRect(-facing*13-3,-31,5,3);
  // Independently animated boots and trouser legs.
  c.fillStyle='#253c50';round(c,-10,-13,9,13+walk*.6,3);c.fill();c.stroke();round(c,3,-13,9,13-walk*.6,3);c.fill();c.stroke();c.fillStyle='#101f2c';round(c,-13,-3+walk*.6,13,7,3);c.fill();round(c,2,-3-walk*.6,14,7,3);c.fill();c.fillStyle='#4d6974';c.fillRect(-11,2+walk*.6,10,1.5);c.fillRect(4,2-walk*.6,10,1.5);
  const suit=c.createLinearGradient(-14,-38,13,-8);suit.addColorStop(0,'#506575');suit.addColorStop(.5,'#314958');suit.addColorStop(1,'#203645');c.fillStyle=suit;round(c,-13,-35,27,26,7);c.fill();c.stroke();c.fillStyle=color;round(c,-12,-34,7,20,2);c.fill();round(c,7,-34,6,20,2);c.fill();c.fillStyle='#e5f3d1';c.fillRect(-12,-22,25,3);c.fillStyle='#121f2b';c.fillRect(-12,-12,25,4);c.fillStyle='#84918b';c.fillRect(-2,-13,6,5);c.fillStyle='#162834';c.fillRect(-3,-32,7,9);c.fillStyle='#6ce3ed';c.fillRect(-1,-29,3,2);
  const skin=['#dbb18b','#a97959','#efc6a4','#bd936e'][u.variant%4];c.fillStyle=skin;round(c,-11,-56,23,23,8);c.fill();c.stroke();c.fillStyle='#ffffff22';round(c,-9,-54,8,14,4);c.fill();c.fillStyle='#142d3d';round(c,-13,-49,27,10,4);c.fill();c.stroke();const glass=c.createLinearGradient(-10,-49,10,-39);glass.addColorStop(0,'#bbf6f1');glass.addColorStop(.4,'#5da6bc');glass.addColorStop(1,'#23455e');c.fillStyle=glass;round(c,-10,-47,20,6,2);c.fill();c.fillStyle='#ecfffa';c.fillRect(-7,-46,4,1.5);c.fillStyle=skin;c.beginPath();c.ellipse(facing*12,-39,3,3.5,0,0,TAU);c.fill();line(c,[[facing*3,-35],[facing*7,-35]],'#704d3e',1);
  const hat=c.createLinearGradient(-15,-65,12,-50);hat.addColorStop(0,color);hat.addColorStop(.6,color);hat.addColorStop(1,'#637369');c.fillStyle=hat;c.beginPath();c.ellipse(0,-54,16,13,0,Math.PI,TAU);c.closePath();c.fill();c.stroke();round(c,-18,-55,36,5,2);c.fill();c.stroke();c.fillStyle='#ffffff55';round(c,-3,-67,6,12,2);c.fill();c.fillStyle='#344953';round(c,8,-62,9,5,2);c.fill();c.fillStyle='#d4ffec';c.fillRect(14,-61,3,3);
  if(u.variant%4===1){c.fillStyle='#263c4a';round(c,-16,-49,6,12,3);c.fill();line(c,[[-14,-40],[-17,-32],[-8,-32]],'#152a38',2);}if(u.variant%4===2){c.fillStyle='#d6d9c1';c.fillRect(-11,-63,5,3);c.fillRect(6,-63,5,3);}if(u.variant%4===3){c.fillStyle='#324b5a';round(c,-13,-40,25,8,2);c.fill();c.fillStyle='#849894';for(let i=0;i<4;i++)c.fillRect(-8+i*5,-38,2,4);}
  // Tool and gloved hands follow the aiming angle.
  const index=active&&g?g.weapon:0,w=WEAPONS[index],aim=active&&g&&['aim','intro'].includes(g.phase)?-g.angle*Math.PI/180:facing>0?-.28:-Math.PI+.28;c.save();c.translate(facing*7,-27);c.rotate(aim);c.fillStyle='#213645';c.strokeStyle='#091e2b';c.lineWidth=1.5;
  if(index===9){round(c,-3,-10,25,20,4);c.fill();c.stroke();c.fillStyle='#91efb6';c.fillRect(7,-6,4,12);c.fillRect(3,-2,12,4);}
  else{round(c,0,-6,index===3?40:30,12,4);c.fill();c.stroke();c.fillStyle='#70898f';round(c,4,-5,13,9,2);c.fill();c.fillStyle='#152b3a';c.fillRect(20,-9,11,18);c.fillStyle=w.color;c.fillRect(22,-6,3,12);c.fillStyle='#9bbbbb';c.fillRect(index===3?34:29,-4,index===3?15:7,8);c.fillStyle=w.color;c.shadowColor=w.color;c.shadowBlur=6;c.fillRect(index===3?48:34,-3,3,6);c.shadowBlur=0;if(index===1||index===4){c.fillStyle=w.color;round(c,10,-10,8,20,3);c.fill();}}
  c.fillStyle='#b58f6f';c.beginPath();c.arc(5,5,5,0,TAU);c.fill();c.strokeStyle='#304353';c.lineWidth=2;c.stroke();c.restore();
  if(u.hurt>0){c.globalAlpha=u.hurt*.6;c.fillStyle='#ffffff';round(c,-15,-55,30,49,10);c.fill();}c.restore();
 }
 aim(){const g=this.game,c=this.ctx;if(!g.active||g.active.hp<=0||g.phase!=='aim'||g.teams[g.teamIndex].bot)return;const u=g.active,w=WEAPONS[g.weapon];
  if(w.type==='repair')return;
  if(w.type==='chain'){c.strokeStyle=w.color+'55';c.lineWidth=1.5;c.setLineDash([5,9]);c.beginPath();c.arc(u.x,u.y-24,w.radius,0,TAU);c.stroke();c.setLineDash([]);return;}
  if(w.type==='airstrike'&&g.aimTarget){const x=g.aimTarget.x,y=g.terrain.surface(x);c.strokeStyle=w.color;c.lineWidth=2;c.setLineDash([6,7]);line(c,[[x,y-250],[x,y+15]],w.color+'99',2);c.setLineDash([]);c.beginPath();c.ellipse(x,y-2,125,18,0,0,TAU);c.stroke();for(let i=-2;i<=2;i++)line(c,[[x+i*60,y-80],[x+i*60,y-54],[x+i*60-5,y-61]],w.color,2);return;}
  const key=[Math.round(u.x),Math.round(u.y),g.angle.toFixed(1),g.power.toFixed(1),g.weapon,g.terrain.version].join('/');
  if(!this.aimCache||this.aimCache.key!==key){const p=g.makeProjectile(u,g.angle,g.power,g.weapon),points=[];for(let i=0;i<180;i++){const result=g.traceStep(p,1/60,true);if(i%5===0)points.push({x:p.x,y:p.y});if(result)break;}this.aimCache={key,points};}
  c.fillStyle=w.color;const points=this.aimCache.points;for(let i=0;i<points.length;i++){c.globalAlpha=.65*(1-i/(points.length+4));c.beginPath();c.arc(points[i].x,points[i].y,i%4===0?3:1.8,0,TAU);c.fill();}c.globalAlpha=1;
 }
 objects(){const c=this.ctx,g=this.game;for(const b of g.barrels)if(b.alive){c.save();c.translate(b.x,b.y);c.fillStyle='#623f39';c.strokeStyle='#181f26';c.lineWidth=2;round(c,-11,-29,22,29,4);c.fill();c.stroke();c.fillStyle='#df8d63';c.fillRect(-10,-23,20,3);c.fillRect(-10,-7,20,3);c.fillStyle='#ffcd8a';c.font='bold 16px Segoe UI';c.textAlign='center';c.fillText('ϟ',0,-10);c.restore();}
  for(const box of g.crates)if(box.alive){c.save();c.translate(box.x,box.y);if(!box.landed){c.fillStyle=box.kind==='health'?'#a2ddc7cc':'#e8ba7ecc';c.beginPath();c.arc(0,-60,35,Math.PI,TAU);c.fill();for(let x of [-33,-12,12,33])line(c,[[x,-60],[x*.25,-18]],'#dfe7d38c',1);}c.fillStyle='#354e56';c.strokeStyle='#071c28';c.lineWidth=2;round(c,-15,-27,30,27,4);c.fill();c.stroke();c.fillStyle=box.kind==='health'?'#91efb6':'#ffce84';c.fillRect(-13,-25,26,4);c.font='bold 20px Segoe UI';c.textAlign='center';c.fillText(box.kind==='health'?'✚':'ϟ',0,-5);c.restore();}
 }
 projectiles(){const c=this.ctx;for(const p of this.game.projectiles){if(p.delay>0)continue;const w=WEAPONS[p.weapon];for(let i=1;i<p.trail.length;i++){c.globalAlpha=i/p.trail.length*.4;line(c,[[p.trail[i-1].x,p.trail[i-1].y],[p.trail[i].x,p.trail[i].y]],w.color,1+i/p.trail.length*4);}c.globalAlpha=1;c.save();c.translate(p.x,p.y);c.rotate(p.type==='grenade'?this.time*8:Math.atan2(p.vy,p.vx));c.shadowColor=w.color;c.shadowBlur=19;c.fillStyle=w.color;if(p.type==='grenade'||p.type==='bomblet'){round(c,-7,-6,14,12,3);c.fill();c.shadowBlur=0;c.fillStyle='#344650';c.fillRect(-3,-7,3,14);c.fillRect(3,-7,3,14);}else{c.beginPath();c.moveTo(13,0);c.lineTo(3,-6);c.lineTo(-11,-5);c.lineTo(-7,0);c.lineTo(-11,5);c.lineTo(3,6);c.closePath();c.fill();c.shadowBlur=0;c.fillStyle='#f6f9ce';c.fillRect(-14,-3,6+Math.random()*8,6);}c.restore();}}
 effects(){const c=this.ctx;for(const p of this.particles){const alpha=clamp(p.life/p.max,0,1);c.globalAlpha=alpha*(p.kind==='smoke'?.32:1);c.fillStyle=p.color;if(p.kind==='smoke'){c.beginPath();c.arc(p.x,p.y,p.size*(2-alpha),0,TAU);c.fill();}else if(p.kind==='debris'){c.save();c.translate(p.x,p.y);c.rotate(p.rotation);c.fillRect(-p.size/2,-p.size/2,p.size,p.size*.7);c.restore();}else{c.beginPath();c.arc(p.x,p.y,p.size*alpha,0,TAU);c.fill();}}c.globalAlpha=1;
  for(const r of this.rings){let p=1-r.life/r.max;c.globalAlpha=(1-p)*.75;c.strokeStyle=r.color;c.lineWidth=5*(1-p)+1;c.beginPath();c.arc(r.x,r.y,r.r*(.3+p),0,TAU);c.stroke();const glow=c.createRadialGradient(r.x,r.y,0,r.x,r.y,Math.max(1,r.r*(1+p)));glow.addColorStop(0,r.color+'a0');glow.addColorStop(.35,r.color+'30');glow.addColorStop(1,r.color+'00');c.fillStyle=glow;c.fillRect(r.x-r.r*2,r.y-r.r*2,r.r*4,r.r*4);if(p<.18){c.fillStyle='#fffbd4';c.beginPath();c.arc(r.x,r.y,r.r*.55,0,TAU);c.fill();}}c.globalAlpha=1;
  for(const b of this.bolts){c.globalAlpha=Math.min(1,b.life*3);let points=[[b.x1,b.y1]];for(let j=1;j<12;j++)points.push([b.x1+(b.x2-b.x1)*j/12+(Math.random()-.5)*21,b.y1+(b.y2-b.y1)*j/12+(Math.random()-.5)*21]);points.push([b.x2,b.y2]);c.shadowBlur=18;c.shadowColor=b.color;line(c,points,b.color,6);line(c,points,'#efffff',2);c.shadowBlur=0;}c.globalAlpha=1;
 }
 water(){const c=this.ctx,y=this.game.water;const grad=c.createLinearGradient(0,y,0,y+240);grad.addColorStop(0,MAPS[this.map].water+'c8');grad.addColorStop(.1,'#28546cd9');grad.addColorStop(1,'#102d45fc');c.fillStyle=grad;c.fillRect(0,y,W,H+500);c.fillStyle='#b4e4dd15';c.fillRect(0,y+3,W,6);c.strokeStyle='#baf2eac0';c.lineWidth=2;c.beginPath();for(let x=0;x<=W;x+=10){let yy=y+Math.sin(x*.035+(this.reduced?0:this.time*1.8))*2.2;x?c.lineTo(x,yy):c.moveTo(x,yy);}c.stroke();for(let i=0;i<90;i++){const x=(i*117+this.time*8)%W,yy=y+14+i%8*14;c.strokeStyle='#bee6e320';line(c,[[x,yy],[x+16+i%5*13,yy]],'#bee6e320',1);}}
 labels(){const c=this.ctx,g=this.game;for(const u of g.units){if(u.hp<=0)continue;const p=this.worldToScreen(u.x,u.y-76);if(p.x<-50||p.x>this.width+50||p.y<this.area.top-20||p.y>this.area.bottom)continue;const active=u===g.active,color=COLORS[u.team];if((this.cam.z<.43||this.area.height<185)&&!active){c.fillStyle=color;c.beginPath();c.arc(p.x,p.y+6,2.5,0,TAU);c.fill();continue;}c.font=(active?'700 ':'600 ')+'10px Segoe UI';c.textAlign='center';const width=Math.max(50,c.measureText(u.name).width+20);c.fillStyle=active?'#102c3eef':'#0c1d2bc7';round(c,p.x-width/2,p.y-15,width,28,5);c.fill();if(active){c.strokeStyle=color+'bb';c.lineWidth=1;c.stroke();c.fillStyle=color;c.beginPath();c.moveTo(p.x-4,p.y-23);c.lineTo(p.x+4,p.y-23);c.lineTo(p.x,p.y-18);c.fill();}c.fillStyle=color;c.fillText(u.name,p.x,p.y-4);c.fillStyle='#ffffff18';round(c,p.x-width/2+5,p.y+3,width-10,3,1);c.fill();c.fillStyle=color;round(c,p.x-width/2+5,p.y+3,(width-10)*u.hp/u.maxHp,3,1);c.fill();if(active||this.cam.z>.75){c.font='9px Consolas';c.fillStyle='#edf4eb';c.fillText(Math.ceil(u.hp),p.x,p.y-21);}}
  for(const t of this.texts){const p=this.worldToScreen(t.x,t.y);c.globalAlpha=Math.min(1,t.life);c.font='800 '+(t.text.length>8?12:20)+'px Segoe UI';c.textAlign='center';c.strokeStyle='#0a1d29';c.lineWidth=4;c.strokeText(t.text,p.x,p.y);c.fillStyle=t.color;c.fillText(t.text,p.x,p.y);}c.globalAlpha=1;c.textAlign='left';
  for(const p of g.projectiles){if(p.delay>0)continue;const s=this.worldToScreen(p.x,p.y);if(s.y<this.area.top+12){const x=clamp(s.x,25,this.width-25);c.fillStyle=WEAPONS[p.weapon].color;c.beginPath();c.moveTo(x,this.area.top+4);c.lineTo(x-5,this.area.top+13);c.lineTo(x+5,this.area.top+13);c.fill();c.font='9px Consolas';c.textAlign='center';c.fillText(Math.round((this.area.top-s.y)/this.cam.z)+' m',x,this.area.top+26);}}
 }
 minimap(){const c=this.mc,g=this.game,w=this.mini.width,h=this.mini.height;c.clearRect(0,0,w,h);c.fillStyle='#0a1a28';c.fillRect(0,0,w,h);c.drawImage(this.terrainCanvas,0,0,W,H,0,0,w,h);c.fillStyle='#5393ae70';c.fillRect(0,g.water/H*h,w,h);for(const u of g.units)if(u.hp>0){c.fillStyle=COLORS[u.team];c.beginPath();c.arc(u.x/W*w,u.y/H*h,u===g.active?3:1.8,0,TAU);c.fill();}for(const p of g.projectiles){c.fillStyle='#ffffff';c.fillRect(p.x/W*w-1,p.y/H*h-1,2,2);}const left=this.cam.x-this.width/(2*this.cam.z),top=this.cam.y-this.area.height/(2*this.cam.z);c.strokeStyle='#d9efddaa';c.lineWidth=1;c.strokeRect(left/W*w,top/H*h,this.width/this.cam.z/W*w,this.area.height/this.cam.z/H*h);}
 menu(){const c=this.ctx;if(this.width<900)return;const baseX=this.width*.47,baseY=this.height*.77;const chars=[{dx:-60,s:1.65,color:COLORS[1],variant:1},{dx:50,s:1.7,color:COLORS[3],variant:3},{dx:-3,s:2.15,color:COLORS[0],variant:0}];for(const u of chars){this.engineer(c,{x:baseX+u.dx,y:baseY+(u.s>2?14:0),id:u.variant,variant:u.variant,ground:true,walk:0,facing:1,hp:120,hurt:0,landing:0},u.color,false,u.s);}}
 draw(){const c=this.ctx;c.setTransform(this.dpr,0,0,this.dpr,0,0);this.background();if(!this.game){this.menu();return;}this.updateTerrain();c.save();c.beginPath();c.rect(0,this.area.top,this.width,this.area.height);c.clip();c.save();const shake=this.reduced?0:this.shake;c.translate(this.width/2+(Math.random()-.5)*shake,this.area.cy+(Math.random()-.5)*shake);c.scale(this.cam.z,this.cam.z);c.translate(-this.cam.x,-this.cam.y);this.decorations();c.drawImage(this.terrainCanvas,0,0);this.objects();this.aim();for(const u of this.game.units)if(u.hp>0){const p=this.worldToScreen(u.x,u.y);if(p.x>-80&&p.x<this.width+80)this.engineer(c,u,COLORS[u.team],u===this.game.active);}this.projectiles();this.effects();this.water();c.restore();this.labels();
  if(this.map==='tidal'&&!this.reduced){for(let i=0;i<90;i++){let x=(i*59+this.time*125)%this.width,y=(i*103+this.time*420)%this.height;line(c,[[x,y],[x-5,y+15]],'#c1dce52b',1);}}
  if(this.map==='alpine'&&!this.reduced){c.fillStyle='#e5f8f359';for(let i=0;i<65;i++){let x=(i*97+Math.sin(this.time*.4+i)*14+this.time*9)%this.width,y=(i*47+this.time*(10+i%3*6))%this.height;c.beginPath();c.arc(x,y,1+i%2*.5,0,TAU);c.fill();}}
  c.restore();if(this.flash>0&&!this.reduced){c.fillStyle='#efffd8';c.globalAlpha=this.flash;c.fillRect(0,this.area.top,this.width,this.area.height);c.globalAlpha=1;}this.minimap();
 }
}
root.CB.Renderer=Renderer;
})(globalThis);
