import {TAMANOS_MINAS,minasNueva,abrirMina,bandera,acorde,cuenta,serpienteNueva,girar,avanzar} from './motores.js';
import {suena,ambientar} from '../sonido.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dirs={ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1},ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0},w:{x:0,y:-1},s:{x:0,y:1},a:{x:-1,y:0},d:{x:1,y:0}};
export function crearSolo({juego,usuario,guardar,watch,volver}){
 const minas=juego==='minas';let host,s=null,activo=false,pausa=false,muerto=false,raf=0,ultimo=0,tiempo=0,acumulado=0,marcar=false,off=null,categoria='',partida='',resultado=null,guardando=false;
 let lista=[],errorRanking='',ultimoSegundo=-1;
 const $=id=>host.querySelector('#'+id);
 function montar(el){host=el;host.innerHTML=`<section class="sp ${minas?'sp-minas':'sp-snake'}">
 <header class="sp-hero"><button id="spVolver" class="sp-link">← Todos los juegos</button><span class="sp-kicker">SOLO / ARCADE LAB</span><h1>${minas?'MINE<span>FALL</span>':'NEON<span>COIL</span>'}</h1><p>${minas?'Lee el terreno. Domina lo desconocido.':'Un movimiento más. Un récord nuevo.'}</p><div class="sp-emblema" aria-hidden="true">${minas?'✦':'ϟ'}</div></header>
 <div class="sp-layout"><main><div class="sp-config">
 ${minas?`<label>Territorio<select id="spTamano"><option value="explorador">Explorador · 9 × 9</option><option value="veterano">Veterano · 16 × 16</option><option value="leyenda">Leyenda · 30 × 16</option></select></label><label>Variante<select id="spModo"><option value="clasico">Clásico · 8 vecinos</option><option value="cruz">Táctico · en cruz</option></select></label>`:`<label>Sector<select id="spModo"><option value="clasico">Clásico</option><option value="portal">Portales · bordes conectados</option><option value="ruinas">Ruinas · obstáculos</option></select></label><label>Velocidad<select id="spVelocidad"><option value="lenta">Órbita · suave</option><option value="media" selected>Pulso · media</option><option value="rapida">Vértigo · rápida</option></select></label>`}
 <button id="spInicio" class="sp-primary">Iniciar expedición ↗</button></div>
 <div class="sp-hud"><div><small>${minas?'MINAS RESTANTES':'PUNTOS'}</small><b id="spPuntos">—</b></div><div><small>TIEMPO</small><b id="spTiempo">00:00</b></div><div><small>RÉCORD PERSONAL</small><b id="spRecord">—</b></div><button id="spPausa" disabled>Pausar</button>${minas?'<button id="spBandera" aria-pressed="false">⚑ Marcar</button>':''}</div>
 <div class="sp-arena"><div id="spTablero" class="${minas?'sp-scroll':'sp-canvas-wrap'}">${minas?'':'<canvas id="spCanvas" width="720" height="720" aria-label="Tablero de Snake" role="img"></canvas>'}</div><div id="spCapa" class="sp-capa"><span class="sp-kicker">${minas?'CADA CASILLA ES UNA DECISIÓN':'ENCUENTRA TU RITMO'}</span><h2>${minas?'El primer paso es seguro.':'Persigue la luz.'}</h2><p>Elige un modo y comienza.</p></div></div>
 ${!minas?'<div class="sp-pad" aria-label="Controles de dirección"><button data-dir="ArrowUp" aria-label="Arriba">↑</button><button data-dir="ArrowLeft" aria-label="Izquierda">←</button><button data-dir="ArrowDown" aria-label="Abajo">↓</button><button data-dir="ArrowRight" aria-label="Derecha">→</button></div>':''}
 <div id="spEstado" role="status" aria-live="polite"></div>
 <details class="sp-instrucciones" open><summary>Domina el juego</summary><p>${minas?'Revela las casillas sin minas. El primer clic y sus vecinos son seguros. Clic derecho o «Marcar» para poner banderas. Pulsa un número con todas sus banderas colocadas para abrir sus vecinos. En modo táctico, los números cuentan solo arriba, abajo, izquierda y derecha. Flechas para navegar; Enter para revelar y F para marcar.':'Flechas, WASD, gestos o botones para dirigir. Recoge energía, crece y evita tu cuerpo. Portales conecta los bordes; Ruinas añade paredes interiores. Espacio pausa la partida. Cada energía vale 100 puntos.'}</p><p>${minas?'Puntúan las expediciones completadas: 100 puntos por casilla segura, más hasta 10.000 por rapidez.':'La clasificación conserva tu mejor puntuación; en empate gana la partida más corta.'} Cada modo tiene su propia tabla.</p></details></main>
 <aside class="sp-ranking"><span class="sp-kicker">HALL OF FAME</span><h2>Los mejores<br>de este sector.</h2><p id="spCategoria"></p><ol id="spLista"></ol><p class="sp-nota">Tu récord se sincroniza con tu cuenta al terminar. Las partidas se calculan en el navegador.</p></aside></div></section>`;
 $('spVolver').onclick=volver;$('spInicio').onclick=iniciar;$('spPausa').onclick=()=>pausar(!pausa);
 for(const el of host.querySelectorAll('select'))el.onchange=cambiarCategoria;
 if(minas){$('spBandera').onclick=()=>{marcar=!marcar;$('spBandera').setAttribute('aria-pressed',String(marcar));};$('spTablero').onclick=e=>accion(e,false);$('spTablero').oncontextmenu=e=>{e.preventDefault();accion(e,true);};$('spTablero').onkeydown=teclasMinas;}
 else {for(const b of host.querySelectorAll('[data-dir]'))b.onclick=()=>direccion(dirs[b.dataset.dir]);let origen=null;const canvas=$('spCanvas');canvas.onpointerdown=e=>{origen={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);};canvas.onpointerup=e=>{if(!origen)return;const dx=e.clientX-origen.x,dy=e.clientY-origen.y;origen=null;if(Math.max(Math.abs(dx),Math.abs(dy))<12)return;direccion(Math.abs(dx)>Math.abs(dy)?{x:Math.sign(dx),y:0}:{x:0,y:Math.sign(dy)});};canvas.onpointercancel=()=>origen=null;}
 document.addEventListener('keydown',teclado);document.addEventListener('visibilitychange',visibilidad);cambiarCategoria();raf=requestAnimationFrame(tick);
 }
 function clave(){return minas?'minas-'+$('spTamano').value+'-'+$('spModo').value:'snake-'+$('spModo').value+'-'+$('spVelocidad').value;}
 function cambiarCategoria(){categoria=clave();if(off)off();lista=[];errorRanking='';pintarRanks();const key=categoria;$('spCategoria').textContent=[...host.querySelectorAll('select')].map(x=>x.selectedOptions[0].textContent).join(' / ');off=watch(categoria,(filas,error)=>{if(muerto||categoria!==key)return;lista=filas||[];errorRanking=error?'No se pudo cargar la clasificación.':'';pintarRanks();});if(!activo){resultado=local();if(resultado)sincronizar();}}
 function local(){try{return JSON.parse(localStorage.getItem('jg.solo.'+usuario.uid+'.'+categoria)||'null');}catch{return null;}}
 function pintarRanks(){const orden=[...lista].sort((a,b)=>b.puntos-a.puntos||a.tiempo-b.tiempo||a.uid.localeCompare(b.uid));$('spLista').innerHTML=errorRanking?`<li>${errorRanking}</li>`:orden.length?orden.slice(0,10).map((f,i)=>`<li class="${f.uid===usuario.uid?'sp-yo':''}"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(f.nombre||'Jugador')}</span><strong>${f.puntos.toLocaleString()}</strong></li>`).join(''):'<li>El primer récord puede ser tuyo.</li>';
 const propio=lista.find(x=>x.uid===usuario.uid),l=local();$('spRecord').textContent=Math.max(propio?.puntos||0,l?.puntos||0).toLocaleString();}
 function iniciar(){s=minas?minasNueva($('spTamano').value,$('spModo').value):serpienteNueva($('spModo').value);activo=true;pausa=false;tiempo=0;acumulado=0;ultimo=0;ultimoSegundo=-1;resultado=null;partida=crypto.randomUUID();marcar=false;$('spTiempo').textContent='00:00';$('spInicio').disabled=true;for(const el of host.querySelectorAll('select'))el.disabled=true;$('spPausa').disabled=false;$('spPausa').textContent='Pausar';$('spCapa').hidden=true;$('spEstado').textContent='';if(minas){$('spBandera').setAttribute('aria-pressed','false');montarMinas();}ambientar(juego);suena('entra');pintar();}
 function montarMinas(){const t=$('spTablero');t.innerHTML=`<div class="sp-minas-grid" style="--cols:${s.w}" role="group" aria-label="Campo de minas">${Array.from({length:s.w*s.h},(_,i)=>`<button data-celda="${i}" aria-label="Fila ${Math.floor(i/s.w)+1}, columna ${i%s.w+1}, oculta" tabindex="${i===0?0:-1}"></button>`).join('')}</div>`;}
 function accion(e,derecha){if(!activo||pausa||!minas)return;const b=e.target.closest('[data-celda]');if(!b)return;const i=Number(b.dataset.celda);if(derecha||marcar){bandera(s,i);suena('clic');}else if(s.abiertas.has(i))acorde(s,i);else{abrirMina(s,i);suena('ficha');}pintar();if(s.estado==='gana'||s.estado==='pierde')fin();}
 function teclasMinas(e){const b=e.target.closest('[data-celda]');if(!b)return;const i=Number(b.dataset.celda);if(e.key.toLowerCase()==='f'){e.preventDefault();accion(e,true);return;}if(!dirs[e.key])return;e.preventDefault();const d=dirs[e.key],x=Math.max(0,Math.min(s.w-1,i%s.w+d.x)),y=Math.max(0,Math.min(s.h-1,Math.floor(i/s.w)+d.y));b.tabIndex=-1;const n=host.querySelector(`[data-celda="${y*s.w+x}"]`);n.tabIndex=0;n.focus();}
 function direccion(d){if(activo&&!pausa)girar(s,d);}
 function teclado(e){if(!activo||/SELECT|INPUT|TEXTAREA/.test(e.target.tagName))return;if(!minas&&dirs[e.key]){e.preventDefault();direccion(dirs[e.key]);}else if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();pausar(!pausa);}}
 function visibilidad(){if(document.hidden&&activo)pausar(true);}
 function pausar(valor){if(!activo)return;pausa=valor;ultimo=0;$('spPausa').textContent=pausa?'Continuar':'Pausar';$('spCapa').hidden=!pausa;if(pausa){$('spCapa').innerHTML='<span class="sp-kicker">RESPIRA</span><h2>En pausa.</h2><button id="spContinuar" class="sp-primary">Continuar</button>';$('spContinuar').onclick=()=>pausar(false);}ambientar(pausa?'':juego);}
 function tick(t){if(muerto)return;if(!ultimo)ultimo=t;const dt=Math.max(0,t-ultimo);ultimo=t;if(activo&&!pausa){if(!minas||s.estado==='jugando')tiempo+=dt;if(!minas){acumulado+=Math.min(300,dt);const ms={lenta:180,media:120,rapida:80}[$('spVelocidad').value];while(acumulado>=ms&&activo){acumulado-=ms;avanzar(s);if(s.estado!=='jugando')fin();}pintarSnake();}const seg=Math.floor(tiempo/1000);if(seg!==ultimoSegundo){ultimoSegundo=seg;$('spTiempo').textContent=String(Math.floor(seg/60)).padStart(2,'0')+':'+String(seg%60).padStart(2,'0');}}raf=requestAnimationFrame(tick);}
 function pintar(){if(minas){for(const b of host.querySelectorAll('[data-celda]')){const i=Number(b.dataset.celda),ab=s.abiertas.has(i),flag=s.banderas.has(i),mina=s.estado==='pierde'&&s.minas.has(i),n=ab?cuenta(s,i):0;b.className=(ab?'abierta n'+n:'')+(flag?' bandera':'')+(mina?' mina':'')+(i===s.golpe?' golpe':'');b.textContent=mina?'✦':flag?'⚑':ab&&n?n:'';b.setAttribute('aria-label',`Fila ${Math.floor(i/s.w)+1}, columna ${i%s.w+1}: ${mina?'mina':flag?'bandera':ab?n+' minas vecinas':'oculta'}`);}$('spPuntos').textContent=s.n-s.banderas.size;}else pintarSnake();}
 function pintarSnake(){const c=$('spCanvas').getContext('2d'),u=30;c.fillStyle='#070b18';c.fillRect(0,0,720,720);c.strokeStyle='#172037';c.lineWidth=1;for(let i=0;i<=24;i++){c.beginPath();c.moveTo(i*u,0);c.lineTo(i*u,720);c.moveTo(0,i*u);c.lineTo(720,i*u);c.stroke();}for(const p of s.obstaculos){c.fillStyle='#495274';c.fillRect(p.x*u+2,p.y*u+2,26,26);c.fillStyle='#a1a7c4';c.fillRect(p.x*u+3,p.y*u+3,24,3);}if(s.comida){c.save();c.shadowColor='#ffb958';c.shadowBlur=22;c.fillStyle='#ffcc70';c.beginPath();c.arc(s.comida.x*u+15,s.comida.y*u+15,8+Math.sin(tiempo/180)*2,0,Math.PI*2);c.fill();c.restore();}s.cuerpo.forEach((p,i)=>{c.fillStyle=i?'hsl('+ (170+i*2%90)+' 75% '+Math.max(32,64-i*.6)+'%)':'#e0fff6';c.beginPath();c.roundRect(p.x*u+2,p.y*u+2,26,26,i?7:10);c.fill();});const h=s.cuerpo[0];c.fillStyle='#15322d';for(const q of [-1,1]){c.beginPath();c.arc(h.x*u+15+s.dir.x*7+(s.dir.y?q*6:0),h.y*u+15+s.dir.y*7+(s.dir.x?q*6:0),2.7,0,7);c.fill();}$('spPuntos').textContent=s.puntos.toLocaleString();}
 function fin(){if(!activo)return;activo=false;ambientar('');pintar();const gana=s.estado==='gana',puntos=minas?(gana?(s.w*s.h-s.n)*100+Math.max(0,10000-Math.floor(tiempo/100)):0):s.puntos;suena(gana?'victoria':'derrota');$('spPausa').disabled=true;$('spInicio').disabled=false;for(const el of host.querySelectorAll('select'))el.disabled=false;$('spCapa').hidden=false;$('spCapa').innerHTML=`<span class="sp-kicker">${gana?'SECTOR COMPLETADO':'FIN DE LA EXPEDICIÓN'}</span><h2>${puntos.toLocaleString()} <small>PTS</small></h2><p>${minas&&!gana?'Una mina. Una nueva oportunidad.':'El próximo récord empieza aquí.'}</p><button id="spOtra" class="sp-primary">Jugar otra vez ↗</button><button id="spVer" class="sp-link">Ver tablero</button>`;$('spOtra').onclick=iniciar;$('spVer').onclick=()=>{$('spCapa').hidden=true;};$('spOtra').focus({preventScroll:true});if(puntos>0){resultado={puntos,tiempo:Math.max(1,Math.round(tiempo)),nombre:usuario.name.slice(0,80),partida,categoria};const antes=local();if(!antes||puntos>antes.puntos||puntos===antes.puntos&&resultado.tiempo<antes.tiempo)try{localStorage.setItem('jg.solo.'+usuario.uid+'.'+categoria,JSON.stringify(resultado));}catch{}pintarRanks();sincronizar();}else $('spEstado').textContent='Esta partida no suma puntos al ranking.';}
 async function sincronizar(){if(!resultado||guardando)return;const dato={...resultado};guardando=true;$('spEstado').textContent='Guardando récord…';try{await guardar(dato.categoria,usuario.uid,dato);if(!muerto&&resultado?.partida===dato.partida)$('spEstado').textContent='Récord sincronizado con tu cuenta.';}catch{if(!muerto&&resultado?.partida===dato.partida){$('spEstado').innerHTML='No se pudo sincronizar. Tu récord sigue guardado en este dispositivo. <button id="spReintentar">Reintentar</button>';$('spReintentar').onclick=sincronizar;}}finally{guardando=false;if(!muerto&&resultado&&resultado.partida!==dato.partida)sincronizar();}}
 function destruir(){muerto=true;cancelAnimationFrame(raf);if(off)off();document.removeEventListener('keydown',teclado);document.removeEventListener('visibilitychange',visibilidad);ambientar('');host.innerHTML='';}
 return {montar,destruir};
}
